### ISSUE TITLE
Request MySejahtera Checkins by State

### ISSUE THREAD

**Issue by aithee** [MoH-Malaysia/covid19-public#10]
We would like to request a granular data from MySejahtera on Checkins by State and District. Currently only the National Level of the MySejahtera and HIDE data points are available. 

These data will also show the pattern of clusters vs movements. 
Or the use of MySejahtera vs Non MySejahtera recorded clusters.

Thank you

**Comment by MoH-Malaysia** [comment]
We have collated your request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md). Thank you for your input!
