### ISSUE TITLE
Add columns in the tests_malaysia.csv to indicate vaccinated info

### ISSUE THREAD

**Issue by tanchinluh** [MoH-Malaysia/covid19-public#100]
tests_malaysia.csv should have columns to indicate the test subjects vaccination history, number of tests with no vaccination history, 1 dose, and 2 doses.

**Comment by MoH-Malaysia** [comment]
Please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
