### ISSUE TITLE
Data not updated again

### ISSUE THREAD

**Issue by chiacy** [MoH-Malaysia/covid19-public#103]
<img width="1529" alt="Screenshot 2021-08-06 at 4 30 24 PM" src="https://user-images.githubusercontent.com/7408097/128481969-92f974a7-c5a2-41d7-bd1f-3fa3cee4960d.png">

appreciate if you can iron out the data update issue. perhaps you may want to monitor your cron update job, when failed, you should be alerted.

this will avoid problem for your data consumers

thanks

**Comment by MoH-Malaysia** [comment]
Thanks for flagging - we've updated the pipeline.
