### ISSUE TITLE
Data Request: Granular (anonymised, individual-level) data of Positive Cases and Deaths by age, sex, date and state / district

### ISSUE THREAD

**Issue by chez1978** [MoH-Malaysia/covid19-public#104]
Is it possible to provide the data as in the previously shared press statement table format? Thank you!

![IMG-20210716-WA0022](https://user-images.githubusercontent.com/88547262/128528659-b8e54914-ed14-469a-8dc3-4dcac6b084dc.jpg)
![IMG-20210716-WA0024](https://user-images.githubusercontent.com/88547262/128528661-c92bd8ba-e32e-47b6-bf30-ce74dccb8e58.jpg)

**Comment by MoH-Malaysia** [comment]
We'll look into this - if required, you may make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
