### ISSUE TITLE
Data Request  : sporadic value . 

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#105]
We would like to check both side  jkn kedah for district  if possible so we can cross check  value from  moh side and jkn . 

total cases =  sporadic  + cluster   (per day statistic ) 

We would like to know if or how many cases sporadic become a cluster  or stuck as sporadic value .

**Comment by MoH-Malaysia** [comment]
Please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
