### ISSUE TITLE
For MOH Consideration

### ISSUE THREAD

**Issue by dennislamcv1** [MoH-Malaysia/covid19-public#110]
This is an article published in Free Malaysia Today. For MOH consideration:

**Granular data vital to make Covid-19 decisions**

https://www.freemalaysiatoday.com/category/opinion/2021/08/09/granular-data-vital-to-make-covid-19-decisions/

**Comment by MoH-Malaysia** [comment]
We welcome this feedback and all others that help us improve the nation's surveillance and understanding!
