### ISSUE TITLE
The sum in icu.csv is different from STATUS TERKINI COVID-19 MALAYSIA

### ISSUE THREAD

**Issue by Mitsuhiko-Matsukawa** [MoH-Malaysia/covid19-public#113]
May I know the difference?
![image](https://user-images.githubusercontent.com/17040347/128706623-5e992c4e-e2f4-4aa0-a8eb-82ca931cd087.png)
![moh](https://user-images.githubusercontent.com/17040347/128706957-a62b9715-c6c3-4c6d-8f82-76ba86a8a153.jpg)

**Comment by MoH-Malaysia** [comment]
Status terkini reflects reporting as of early afternoon, whereas the data on Github is complete for the day.

**Comment by Mitsuhiko-Matsukawa** [comment]
Your answer is not the correct reason.
I have checked the difference for 7 days but the number of GitHub is always 30-70% larger than that of Status Terikini.
![GitHub_vs_StatusTerkini](https://user-images.githubusercontent.com/17040347/129432115-666b6fe0-c72e-49a2-b790-7a74b2b5d65d.PNG)

Please reopen this issue and answer the right reason.

08/06
![git_0806](https://user-images.githubusercontent.com/17040347/129432133-560f06b7-daaa-4b75-b7f4-df43681223e2.png)
![status_0806](https://user-images.githubusercontent.com/17040347/129432136-b91b0d69-1637-4885-a158-1b5c736ad07b.jpg)

08/07
![git_0807](https://user-images.githubusercontent.com/17040347/129432137-0affa4fd-73e3-4ddb-baab-2962e9d27c5a.png)
![status_0807](https://user-images.githubusercontent.com/17040347/129432141-1dff004c-d144-46fd-af98-4ffd8513aae2.jpg)

08/08
![git_0808](https://user-images.githubusercontent.com/17040347/129432143-166f7e3c-68d6-4fd7-a834-bdcecd0c8687.png)
![status_0808](https://user-images.githubusercontent.com/17040347/129432146-6d829496-5e31-40c3-a0e1-b8c1a52468a6.jpg)

08/09
![git_0809](https://user-images.githubusercontent.com/17040347/129432147-374f0a07-4314-4a55-a713-9162ff4f7c45.png)
![status_0809](https://user-images.githubusercontent.com/17040347/129432149-12acffcd-a4b3-4a24-9dac-b3481e7caf7e.jpg)

08/10
![git_0810](https://user-images.githubusercontent.com/17040347/129432150-5e245e1a-f812-4825-9dd8-2d4cf662bb6b.PNG)
![status_0810](https://user-images.githubusercontent.com/17040347/129432155-e4420f10-d1ef-4910-b9dc-35f4221d160f.jpg)

08/11
![git_0811](https://user-images.githubusercontent.com/17040347/129432156-07fe29bc-7b24-49c4-8a26-e037e6f2aded.PNG)
![status_0811](https://user-images.githubusercontent.com/17040347/129432157-3287d6de-cff5-4c8b-b1b0-829cc3252c9a.jpg)

08/12
![git_0812](https://user-images.githubusercontent.com/17040347/129432159-79a9406b-296b-4bcc-8dac-5e13fd02cb30.PNG)
![status_0812](https://user-images.githubusercontent.com/17040347/129432161-d3b5013f-7ba8-44aa-8c49-237366596698.jpg)

**Comment by NobodyButMe-Haiya** [comment]
> Your answer is not the correct reason.
> I have checked the difference for 7 days but the number of GitHub is always 30-70% larger than that of Status Terikini.
> ![GitHub_vs_StatusTerkini](https://user-images.githubusercontent.com/17040347/129432115-666b6fe0-c72e-49a2-b790-7a74b2b5d65d.PNG)
> 
> Please reopen this issue and answer the right reason.
> 
> 08/06
> ![git_0806](https://user-images.githubusercontent.com/17040347/129432133-560f06b7-daaa-4b75-b7f4-df43681223e2.png)
> ![status_0806](https://user-images.githubusercontent.com/17040347/129432136-b91b0d69-1637-4885-a158-1b5c736ad07b.jpg)
> 
> 08/07
> ![git_0807](https://user-images.githubusercontent.com/17040347/129432137-0affa4fd-73e3-4ddb-baab-2962e9d27c5a.png)
> ![status_0807](https://user-images.githubusercontent.com/17040347/129432141-1dff004c-d144-46fd-af98-4ffd8513aae2.jpg)
> 
> 08/08
> ![git_0808](https://user-images.githubusercontent.com/17040347/129432143-166f7e3c-68d6-4fd7-a834-bdcecd0c8687.png)
> ![status_0808](https://user-images.githubusercontent.com/17040347/129432146-6d829496-5e31-40c3-a0e1-b8c1a52468a6.jpg)
> 
> 08/09
> ![git_0809](https://user-images.githubusercontent.com/17040347/129432147-374f0a07-4314-4a55-a713-9162ff4f7c45.png)
> ![status_0809](https://user-images.githubusercontent.com/17040347/129432149-12acffcd-a4b3-4a24-9dac-b3481e7caf7e.jpg)
> 
> 08/10
> ![git_0810](https://user-images.githubusercontent.com/17040347/129432150-5e245e1a-f812-4825-9dd8-2d4cf662bb6b.PNG)
> ![status_0810](https://user-images.githubusercontent.com/17040347/129432155-e4420f10-d1ef-4910-b9dc-35f4221d160f.jpg)
> 
> 08/11
> ![git_0811](https://user-images.githubusercontent.com/17040347/129432156-07fe29bc-7b24-49c4-8a26-e037e6f2aded.PNG)
> ![status_0811](https://user-images.githubusercontent.com/17040347/129432157-3287d6de-cff5-4c8b-b1b0-829cc3252c9a.jpg)
> 
> 08/12
> ![git_0812](https://user-images.githubusercontent.com/17040347/129432159-79a9406b-296b-4bcc-8dac-5e13fd02cb30.PNG)
> ![status_0812](https://user-images.githubusercontent.com/17040347/129432161-d3b5013f-7ba8-44aa-8c49-237366596698.jpg)

yeah me an answer . sometimes figure  not same with pkd, which to which should have a timestamp  so at least we can figure correct . we dont just build graph , we need something meaningfull to analayze.

**Comment by shenghann** [comment]
@Mitsuhiko-Matsukawa If I were you, I would analyze data on github as the correct one. It is possible that the Status Terkini infographics are generated midday, and hence not the final revision of the data for the day.

**Comment by NobodyButMe-Haiya** [comment]
> @Mitsuhiko-Matsukawa If I were you, I would analyze data on github as the correct one. It is possible that the Status Terkini infographics are generated midday, and hence not the final revision of the data for the day.

that is the reason we need updated timestamp last update which been mention me before upon cluster end date. the problem is are we getting the same raw data from db or concated to horizontal view /materialize view.

**Comment by Mitsuhiko-Matsukawa** [comment]
@shenghann Do you think that patients in ICU increase 40% in the morning and decrease 40% in the afternoon every day? It cannot be happened as patients in ICU normally stay 14-21 days.
![image](https://user-images.githubusercontent.com/17040347/129449763-4a96c19a-0a67-46da-bd75-6c53ed988849.png)

I doubt the data source or the definition is not same. I want to know how they count and which one is correct.
@MoH-Malaysia Please clarify.

**Comment by mnyunus** [comment]
This issue has not been resolved. Any development? 
We need to reconcile the figures.
