### ISSUE TITLE
Number of cases in cases_state.csv on 23 January 2021

### ISSUE THREAD

**Issue by KennethThePro** [MoH-Malaysia/covid19-public#115]
The number of cases in the cases_state.csv is as follow:
Melaka: 78
Kelantan: 278

The official report from [https://kpkesihatan.com/2021/01/23/kenyataan-akhbar-kpk-23-januari-2021-situasi-semasa-jangkitan-penyakit-coronavirus-2019-covid-19-di-malaysia/](url) is as follow:
Melaka: 278
Kelantan: 78

**Comment by MoH-Malaysia** [comment]
Amended with credits!
