### ISSUE TITLE
Origin cluster

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#119]
I check back one of the data  "dah bukit makmur" the first is "Pendang" District . We analyzed the first array comma as origin of cluster. 

Our data cluster active is different then pejabat daerah kuala muda . (12 August 2021)

Dah Batik Industri Sungai Petani (same)
Dah Cendana Industri (same)
Dah Bukit Makmur (not same) (but it started pendang?)
Dah Industri Arang (not same)
Dah Industri Bakar (Same)
Dah 2 Industri Sungai Petani (same)
Dah Tapak Bina Astana(same)
Dah 5 Industri Sungai Petani (same)
Dah 90 Industri Sungai Petani (same)
Dah Saga Industri Sungai Petani (same)
Dah Padang Temusu(same) (But it started pendang ?)
Dah 3/6 Industri Sungai Petani(same)
Dah Kempas(Same)
Dah Tupah Industri Sungai Petani(same)
Dah 2/2 Industri Sungai Petani(Same)
Dah Persiaran SP(same)

**Comment by MoH-Malaysia** [comment]
Documentation does not necessarily list the geographical origin first.

**Comment by NobodyButMe-Haiya** [comment]
if so , something wrong when you try to query i assume. it should be origin first or on how we want to assume origin? the purpose is to collect accurate data on how much  cases  in district first not outside district.
