### ISSUE TITLE
Request data accessible through API 

### ISSUE THREAD

**Issue by ammard2u** [MoH-Malaysia/covid19-public#12]
Hi MOH team, is it possible that we request all these data accessible through API?

thank you for your hardwork MOH team. 👍

**Comment by MoH-Malaysia** [comment]
We'll consider this request, but it should be fairly easy to connect to the data from the static Github link.

For instance, for cluster data, [this link](https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/clusters.csv) would suffice!
