### ISSUE TITLE
Request Daerah Data

### ISSUE THREAD

**Issue by Chan8148** [MoH-Malaysia/covid19-public#124]
Good day, Can provide more daerah of each state covid-19 positive dataset?

**Comment by NobodyButMe-Haiya** [comment]
cluster cvs got those info but there is argument me before the origin of cluster.

**Comment by mjunkmyjunk** [comment]
Would like to extend the request to include the # of tests being conducted at the daerah/district level in addition to the state level. 

Current granularity only up to state level which leaves % positivity rate questionable. Data can be skewed when (more) tests are done at daerahs which has lower positivity rate.

**Comment by mjunkmyjunk** [comment]
PR Done.
https://github.com/MoH-Malaysia/covid19-public/pull/164#issue-731862890

**Comment by MoH-Malaysia** [comment]
There is district data available in the [cases linelist](https://moh-malaysia-covid19.s3.ap-southeast-1.amazonaws.com/linelist_cases.parquet).
