### ISSUE TITLE
PKRC data not available for every day for every state

### ISSUE THREAD

**Issue by mildredve** [MoH-Malaysia/covid19-public#126]
Hi, may I know if this is deliberate?
Eg 2020-03-28, there are only data for 5 states. 
Do we assume that if the other states are not recorded, they're 0? 
![image](https://user-images.githubusercontent.com/61527465/129833369-ec953bc8-d92f-4917-a3cc-52564c647f41.png)

**Comment by MoH-Malaysia** [comment]
Please refer to the documentation - we explain why date-state combinations are not necessarily complete.
