### ISSUE TITLE
daily recovery & death by state

### ISSUE THREAD

**Issue by shamchenkovski** [MoH-Malaysia/covid19-public#128]
requesting daily recovery & death by state from the beginning of pandemic

**Comment by MoH-Malaysia** [comment]
Done.

**Comment by shamchenkovski** [comment]
thanks for updating the data. found one(might be more) issue.

perlis recovered case might need to re-check again. number of recovery starting from 2020-04-17 is a bit odd.

how can 102 patient recovered when they only have 18 total cases?

fast forward to october 2020. the odd problem continue in 2020-10-21. perlis never recorded more than 2 digit cases, yet the number of patient recovered is 2-3 digit.
