### ISSUE TITLE
Difference between PKRC's admitted_pui & hospital's admitted_pui?

### ISSUE THREAD

**Issue by agnes-lyy** [MoH-Malaysia/covid19-public#130]
Dear MoH,

Can you shed more insights on how the admissions of patients under investigation are arranged? E.g. in what situation / condition do patients get arranged to PKRC or hospitals, what's the difference between p.u.i. who are admitted into PKRC & hospitals, etc

**Comment by MoH-Malaysia** [comment]
Usually down to the severity of the case - this determines whether they require hospitalisation or not.
