### ISSUE TITLE
BID column empty

### ISSUE THREAD

**Issue by hathimazman** [MoH-Malaysia/covid19-public#135]
The BID column for State and Malaysia data is empty

**Comment by ngewkokyew** [comment]
Another follow up question for "Brought in Death", is BID subset of "deaths_new"?

**Comment by KennethThePro** [comment]
> Another follow up question for "Brought in Death", is BID subset of "deaths_new"?

From my understanding, BID is a subset of deaths_new

Using one reference from the "From the Desk of the Director-General of Health Malaysia" website, the total deaths on 28 August 2021 is 252. Total deaths in hospital is 220 and brought in dead is 32 (looks like an error in the github data which states 31 on 28 August 2021). 220 + 32 = 252

https://kpkesihatan.com/2021/08/28/kenyataan-akhbar-kpk-28-ogos-2021-situasi-semasa-jangkitan-penyakit-coronavirus-2019-covid-19-di-malaysia/
![image](https://user-images.githubusercontent.com/86338269/131240643-5bfa79c8-304c-4882-adf4-08441f66dc04.png)

**Comment by NobodyButMe-Haiya** [comment]
> The BID column for State and Malaysia data is empty

i just update my site with bid data https://sponline.xyz/kedah.php. got data but not detail as above since as it  given.

**Comment by MoH-Malaysia** [comment]
BID data has been updated - we were simply getting the file ready.

@KennethThePro data may sometimes be revised post-announcement once audits are done - this is entirely normal across the world. Any revisions are transparent in the commit history.

And yep - BID is a subset of the total.
