### ISSUE TITLE
Different total recover: data github vs covid-19.moh.gov.my

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#136]
The total of recovered cases obtained from github data is different from that reported in covid-19.moh.gov.my website. The difference is by 277 cases. On closer inspection of the data, the discrepancies started on 2021-08-10. From this point onward, the daily counts in epidemic/cases_malaysia.csv -> cases_recovered differ from the counts reported in the website. I include a .csv file showing these differences. No issue with data on 2021-08-27 & 28.

[ [recover_diff.csv](https://github.com/MoH-Malaysia/covid19-public/files/7072237/recover_diff.csv) ]

**Comment by ngewkokyew** [comment]
Another follow up question on the recovery data, for Perlis state, as of the latest data (27 Aug) the cumulative incidence case is about 1763 and the cumulative recovered patients are 41166? Why recovered patients greater than diagnosed patients in that particular state?
