### ISSUE TITLE
MySejahtera Profile QR encryption Key

### ISSUE THREAD

**Issue by Bizsmartech** [MoH-Malaysia/covid19-public#137]
Hi, Since it compulsory to check profile of our employees, can we have the MySejahtera encrypted Qr code key so that we can use scanner to decrypt the code and get the user status. This will be way more effecient than visual checking now. I believe many requesting this information.

**Comment by MoH-Malaysia** [comment]
Thank you for the suggestion - we have forwarded it to the MySejahtera team. We are closing this issue as it does not pertain to open data.
