### ISSUE TITLE
26 Aug, 27 Aug RTK-AG Numbers in tests-states.csv, tests-malaysia.csv are duplicated.

### ISSUE THREAD

**Issue by rainyrainyday** [MoH-Malaysia/covid19-public#138]
As can be seen here at [Line 242](https://github.com/MoH-Malaysia/covid19-public/blob/48f13c88fd7534057539309ac6419ac04b4075e0/epidemic/tests_state.csv#L242) and [Line 258](https://github.com/MoH-Malaysia/covid19-public/blob/48f13c88fd7534057539309ac6419ac04b4075e0/epidemic/tests_state.csv#L258) at the current latest commit.

![image](https://user-images.githubusercontent.com/4942033/131342432-b7042476-75b8-4e46-8d47-550593990cb5.png)![image](https://user-images.githubusercontent.com/4942033/131342482-b52f75fc-5d62-4b62-991a-a89bc624cced.png)

Same goes for [tests-malaysia.csv](https://github.com/MoH-Malaysia/covid19-public/blob/48f13c88fd7534057539309ac6419ac04b4075e0/epidemic/tests_malaysia.csv#L582) as well.

**Comment by MoH-Malaysia** [comment]
We have corrected this, with credits to you in [the commit](https://github.com/MoH-Malaysia/covid19-public/commit/bd2031c40b5299c860bbf5ed06d77bdf8df3e0ef) for flagging!
