### ISSUE TITLE
Column Name Documentation and Pull Request

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#140]
Some of column data updated and do hope the documentation is the same with the updated column so we can verified the field is suppose figure. 

A lot of pull request been made do please update as other can see it easily .

**Comment by MoH-Malaysia** [comment]
Thanks for flagging this! Could you highlight where the documentation differs from the variable naming in-file?

**Comment by NobodyButMe-Haiya** [comment]
icu.csv

Field : 

date | state | beds_icu | beds_icu_rep | beds_icu_total | beds_icu_covid | vent | vent_port | icu_covid | icu_pui | icu_noncovid | vent_covid | vent_pui | vent_noncovid

ICU
(got)date: yyyy-mm-dd format; data correct as of 2359hrs on that date
(got)state: name of state, with similar qualification on exhaustiveness of date-state combos as PKRC data
(got)beds_icu: total gazetted ICU beds
(Got)beds_icu_rep: total beds aside from (3) which are temporarily or permanently designated to be under the care of Anaesthesiology & Critical Care departments
(Got)beds_icu_total: total critical care beds available (with related medical infrastructure)
(Got)beds_icu_covid: total critical care beds dedicated for COVID-19
(Got)vent: total available ventilators
(Got)vent_port: total available portable ventilators
(Missing) icu_covid (Maybe icu_x?)
(Missing)icu_pui
(Missing) icu noncovid
(Mssing) vent_covid (maybe vent_x)
(Missing)ven pui
(Mssing)vent_noncovid
(Unknown)icu_x: total number of individuals in category x under intensive care, where x can be suspected/probable, COVID-19 positive, or non-COVID; this is a stock variable
(Unknown)vent_x: total number of individuals in category x on mechanical ventilation, where x can be suspected/probable, COVID-19 positive, or non-COVID; this is a stock variable

The main point I asking this because we want to know status of  (covid  + non covid ) / total bed icu  * 100 .  

For now we only can assume 

(icu_covid + icu_noncovid + icu_pui ) /  bed_icu * 100 . 
** pui we assume as  PUI = Person Under Investigation

My Data show some over 100%  maybe because they increase bed capacity not updated or else.  This data required for some state to proceed to next stage of phase . 
As kinda confuse new management saying vaccination  can transfer to next phase. We not sure which to which indicator will be used.

**selangor media mention kedah over 130% bed capacity  while mine is around 95% on some date. Both using this source of data.

** our source code are public so anybody can review it if wanted to changed it /forked it

**Comment by hathimazman** [comment]
The National Recovery Plan index on ICU cases are very vague. I noticed that by calculating the (icu_covid/beds_icu covid) can get a rough estimate on the meaning of ICU index fo "Terhad", "Sederhana", and "Memadai" as >=70%, <70%, and <=60%. The gap seems quite narrow. However, this is a rough guess, and if you manage to crack this vague 'code' on NRP index do share!

referring to https://pelanpemulihannegara.gov.my/ for the ICU Categories

**Comment by NobodyButMe-Haiya** [comment]
> The National Recovery Plan index on ICU cases are very vague. I noticed that by calculating the (icu_covid/beds_icu covid) can get a rough estimate on the meaning of ICU index fo "Terhad", "Sederhana", and "Memadai" as >=70%, <70%, and <=60%. The gap seems quite narrow. However, this is a rough guess, and if you manage to crack this vague 'code' on NRP index do share!
> 
> referring to https://pelanpemulihannegara.gov.my/ for the ICU Categories

when n9 they said 40%  to move to phase 2 , we only get figure 35% .. but now kedah. hmm unknown with today 2,4k and no pkpd  anything kinda scary.The place of  pkpd seem not usefull because figure keep coming . 

The figure total population is not the same with jkav which vaccination is the same. 

As result, we no idea how to said "terhad","sederhana","memandai"

**Comment by hathimazman** [comment]
> > The National Recovery Plan index on ICU cases are very vague. I noticed that by calculating the (icu_covid/beds_icu covid) can get a rough estimate on the meaning of ICU index fo "Terhad", "Sederhana", and "Memadai" as >=70%, <70%, and <=60%. The gap seems quite narrow. However, this is a rough guess, and if you manage to crack this vague 'code' on NRP index do share!
> > referring to https://pelanpemulihannegara.gov.my/ for the ICU Categories
> 
> when n9 they said 40% to move to phase 2 , we only get figure 35% .. but now kedah. hmm unknown with today 2,4k and no pkpd anything kinda scary.The place of pkpd seem not usefull because figure keep coming .
> 
> The figure total population is not the same with jkav which vaccination is the same.
> 
> As result, we no idea how to said "terhad","sederhana","memandai"

Seems like the parameter used to calculate ICU capacity is correct if crossed referenced with DG's latest tweet on some data updates. The question now is to crack on what index means quantitatively I guess haha.

I checked the population csv file it seams to be consistent for both citf and the kkm one. Which total population are you referring to?

**Comment by NobodyButMe-Haiya** [comment]
> > > The National Recovery Plan index on ICU cases are very vague. I noticed that by calculating the (icu_covid/beds_icu covid) can get a rough estimate on the meaning of ICU index fo "Terhad", "Sederhana", and "Memadai" as >=70%, <70%, and <=60%. The gap seems quite narrow. However, this is a rough guess, and if you manage to crack this vague 'code' on NRP index do share!
> > > referring to https://pelanpemulihannegara.gov.my/ for the ICU Categories
> > 
> > 
> > when n9 they said 40% to move to phase 2 , we only get figure 35% .. but now kedah. hmm unknown with today 2,4k and no pkpd anything kinda scary.The place of pkpd seem not usefull because figure keep coming .
> > The figure total population is not the same with jkav which vaccination is the same.
> > As result, we no idea how to said "terhad","sederhana","memandai"
> 
> Seems like the parameter used to calculate ICU capacity is correct if crossed referenced with DG's latest tweet on some data updates. The question now is to crack on what index means quantitatively I guess haha.
> 
> I checked the population csv file it seams to be consistent for both citf and the kkm one. Which total population are you referring to?

we using population.csv . it not much diff but 0.03% consider as rounding maybe but .
(Kedah)

Jumlah Katil Bukan Icu ? 

DG : 1165
Ours : Non 

Jumlah Penggunaan
DG 95%
Ours : Non

Jumlah Katil Icu 
DG: 104
Ours :147

Penggunaan Icu 
DG : 121%
Ours: 119% 
** either way this over 100% and last few day they increase the bed to see lower figure icu . 

View : https://sponline.xyz/kedah.php
The source code  : https://github.com/NobodyButMe-Haiya/covid19kualamuda/blob/main/kedah.php

The main point is vaccination  calculate to phase 2 or icu . Melaka  kinda odd today  move to Phase 2. N9  their icu is good

**Comment by NobodyButMe-Haiya** [comment]
this is the latest version https://github.com/NobodyButMe-Haiya/covid19-public/blob/main/CONTRIB.md from all the sources make by developer  @MoH-Malaysia  . Please update it

**Comment by garyyeap** [comment]
+1 for pull requests. There will be a lot of conflicts if left out too many PR.

**Comment by NobodyButMe-Haiya** [comment]
> +1 for pull requests. There will be a lot of conflicts if left out too many PR.

unsure when @MoH-Malaysia  will  reply this critical issue.  DG fb saying kedah 102% icu usage while i have no idea where's they got the numbers. 

the only i certain is icu_bed_covid 19 =  same as here.  the infected in icu who know. ?
