### ISSUE TITLE
Breakdown of New Cases By Category (Between Fully Vaccinated and Not Fully Vaccinated) by State

### ISSUE THREAD

**Issue by richardyeow** [MoH-Malaysia/covid19-public#141]
Can we have the breakdown of daily new cases by Category by State split between "Fully Vaccinated" and "Not Fully Vaccinated/Unvaccinated"

**Comment by DexonLee** [comment]
> Can we have the breakdown of daily new cases by Category by State split between "Fully Vaccinated" and "Not Fully Vaccinated/Unvaccinated"

Split between "Fully Vaccinated" and "Not Fully Vaccinated/Unvaccinated" by State seems not avaliable on MOH site, by Category yes.
Some info for contributers: the data of "Fully Vaccinated" and "Not Fully Vaccinated/Unvaccinated" by Category avaliable starting from 27 July 2021.

**Comment by muhdaimanmr** [comment]
Hopefully separated by state with death count also.

**Comment by rainyrainyday** [comment]
I have a spreadsheet with [new case breakdowns by category](https://docs.google.com/spreadsheets/d/e/2PACX-1vTENFMORGrl4xjOTCub_F5w7OX3srzxE3X6qMTDgMN2KHBuztItYme9BiLNtUnM7Kufdclm8wk0a0P6/pubhtml?gid=910323357&single=true) sourced from the daily infographics from 17-July-2021 until 4-September-2021.

**Comment by aminhusni** [comment]
+1 on this. Having more data on cases and deaths in relation to numbers vaccinated or unvaccinated would be nice and more transparent.

**Comment by rizalramly** [comment]
Strongly suggest adding details of vaccine-type as well. This data will be crucial for further analysis especially on death for each vaccine as upload in linelist_deaths. To measure/calculate the impact of vaccine vs death, I strongly believe we need to be fair to the data as well. Just divided with overall cases will be put more justice to the data.

**Comment by Surina69** [comment]
I suggest separating unvaccinated from partially vaccinated and those who completed the second dose but below 14 days from vaccination. We will see a clearer picture of whether the current vaccination shots are really working in our favour. Use Israel's data as a comparison.

**Comment by chez1978** [comment]
Agreed, fairer comparison and if too much to linelist nearly 2 million
cases, a monthly breakdown by various categories (age group, sex, state,
vaxtype (separate for <14 days), can work as well. Ultimately we just want
to calculate the rates correctly.
