### ISSUE TITLE
New cases categorised by age group?

### ISSUE THREAD

**Issue by lowkp** [MoH-Malaysia/covid19-public#151]
I am a paediatrician with KKM and we are seeing increasing cases for those aged below 18yo, the ratio of severe diseases also increased.  However, we don't have this data within KKM as far as I knew. Can we get this data from CPRC statistics: i) New cases by age group (age group category 0-5, 5-11, 12-17yo) and ii) the disease category upon diagnosis?  I see this data is important in planning for vaccinations for teenagers, younger children and the subsequent school reopening. Thanks

**Comment by chez1978** [comment]
We were once able to track that through the daily Health DG press
statement. I hope the github initiative will look into this urgently. It
has been over a month since the information was removed from public access.

**Comment by NobodyButMe-Haiya** [comment]
> I am a paediatrician with KKM and we are seeing increasing cases for those aged below 18yo, the ratio of severe diseases also increased. However, we don't have this data within KKM as far as I knew. Can we get this data from CPRC statistics: i) New cases by age group (age group category 0-5, 5-11, 12-17yo) and ii) the disease category upon diagnosis? I see this data is important in planning for vaccinations for teenagers, younger children and the subsequent school reopening. Thanks

dear doc , most of us requested also . we do hope also. 
** actually they ask us to pull request to issue thing like this https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests
