### ISSUE TITLE
More Granular Data Required

### ISSUE THREAD

**Issue by Renesis88** [MoH-Malaysia/covid19-public#152]
I think for proper analysis and projection, the data needs to be more detailed. Please provide the following data :

1. For all positive cases. Please provide details of whether it is Category 1-5 or if possible in Category 6 for Death in hospital Category 7 Dead on Arrival.
2. Provide details of gender, age, foreigner or Malaysian, comorbidities, status of vaccination [None, 1st dose, 2nd dose, 2nd dose + 14 days], vaccine type

**Comment by NobodyButMe-Haiya** [comment]
1. been requested at pull.
2. 2nd dose + 14 you can generate yourself as my self im lazy but other done it.  i think you need to check citf instead as noted.

**Comment by Renesis88** [comment]
No, the data requested at pull is not as comprehensive as this request. Will KKM be able to provide for every positive case the following ?
Patient 1 : Date, Category, Age, Nationality, Comorbidities, Vaccine Status, Vaccine Type

With this detail, then we can do more comprehensive EDA.

CITF does not have this level of detail either.

**Comment by NobodyButMe-Haiya** [comment]
> No, the data requested at pull is not as comprehensive as this request. Will KKM be able to provide for every positive case the following ?
> Patient 1 : Date, Category, Age, Nationality, Comorbidities, Vaccine Status, Vaccine Type
> 
> With this detail, then we can do more comprehensive EDA.
> 
> CITF does not have this level of detail either.

https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests

**Comment by NofAboi** [comment]
Hi MOH, I require more granular data as follows:
1. covid19 patients category such as vaccination status and vaccine type for each category
2. death cases with vaccination status and vaccine type

I require these data to for my analytics research
https://datastudio.google.com/s/rEVR6brDRCw
