### ISSUE TITLE
Clarification requested on Hospitals Data

### ISSUE THREAD

**Issue by winsonyeap94** [MoH-Malaysia/covid19-public#155]
Dear MoH,

The data you shared has been very useful in supplementing our company's management in decision making and SOP planning to ensure a safer workplace for all staff members.

When analysing the data, we have a question regarding the Hospitals data -- could you share if the **daily admission & bed figures shared on Hospitals include both government and private hospitals, or do the numbers only reflect government hospitals only**?

Additionally, may I know if there is plan to include **daily cases by category (i.e., Cat 1/2/3/4/5) at a state level**? 

Again the data provided has been very useful and it is helping many companies better adapt and prepare for the transition to endemic. Thanks!

**Comment by MoH-Malaysia** [comment]
Only government.
