### ISSUE TITLE
Inconsistent Recovered Cases Count 

### ISSUE THREAD

**Issue by subi10** [MoH-Malaysia/covid19-public#156]
Hi, there are some inconsistencies in the recovered case count and sometimes it is not shown.

below show the recovered case in Penang.. it suppose to show 70k+ on 28 when i run the running total to get the cummulative,,

![image](https://user-images.githubusercontent.com/53784830/132532271-c08acd38-bbb0-4b1b-84e6-769a956f2991.png)

also when cross check with penang covid 19 fb page
![image](https://user-images.githubusercontent.com/53784830/132532533-45dd7418-62c2-4004-aee3-7eefe9363b04.png)

**Comment by MoH-Malaysia** [comment]
We are not responsible for the reporting from other sites.
