### ISSUE TITLE
Suggestion to resolve PR congestion for CONTRIB.md

### ISSUE THREAD

**Issue by tnwei** [MoH-Malaysia/covid19-public#157]
Seeing PRs build up for updating CONTRIB.md where people intend to add projects or add data requests. Noticed that since numbered lists are used for both, nearly all PRs will have merge conflicts as everyone adds their entry to the next available number on master branch. In current state, only the next immediate PR accepted can be merged cleanly.

I suggest changing the numbered lists in CONTRIB to unordered lists, using "+" or "-" as bulletpoints instead. As long as everyone only adds their own line in their PRs, all future PRs can be merged cleanly. As for the current outstanding PRs, merging is no issue once people update their PRs accordingly to match the format.

Just to be explicit with what I mean, here is the before:

```
1) [[Google Data Studio Dashboard]](https://datastudio.google.com/reporting/8ba8d5d5-9a39-4506-af28-7ab8fcd8f8a9)
An extensive dashboard to be used to monitor the state of the Covid-19 outbreak as well as the progress of vaccination (Malaysia as a whole and by state). Data are manually curated on a daily basis and cross-checked with various official sources for validation and verification purposes. By [aidilsfwn](https://github.com/aidilsfwn).
2) [[Google Data Studio Dashboard]](https://datastudio.google.com/s/gIQwV1fDCpg) Positivity Rate Dashboard. By Koh Wyhow.
3) [[Live site]](https://khoohaoyit.github.io/Covid19%20Malaysia%20Heatmap/root.html) Malaysia Covid 19 Heatmap. By [KhooHaoYit](https://github.com/KhooHaoYit/).
```

And here is the after:

```
+ [[Google Data Studio Dashboard]](https://datastudio.google.com/reporting/8ba8d5d5-9a39-4506-af28-7ab8fcd8f8a9)
An extensive dashboard to be used to monitor the state of the Covid-19 outbreak as well as the progress of vaccination (Malaysia as a whole and by state). Data are manually curated on a daily basis and cross-checked with various official sources for validation and verification purposes. By [aidilsfwn](https://github.com/aidilsfwn).
+ [[Google Data Studio Dashboard]](https://datastudio.google.com/s/gIQwV1fDCpg) Positivity Rate Dashboard. By Koh Wyhow.
+ [[Live site]](https://khoohaoyit.github.io/Covid19%20Malaysia%20Heatmap/root.html) Malaysia Covid 19 Heatmap. By [KhooHaoYit](https://github.com/KhooHaoYit/).
```

Wouldn't mind putting in a PR for this if @MoH-Malaysia is onboard.

**Comment by AbelHo** [comment]
I like to suggest creating a Wiki in this repository for contributions, less work for the admin. Crowd sourced supervision for the wiki as well.

**Comment by MoH-Malaysia** [comment]
Excellent suggestion - we've taken this up.

**Comment by MoH-Malaysia** [comment]
@tnwei - definitely onboard, and we welcome any PR to help clear the backlog! Much appreciated :)

**Comment by NobodyButMe-Haiya** [comment]
done. @MoH-Malaysia  .. we have create the pull request .

**Comment by chengkangzai** [comment]
@NobodyButMe-Haiya i believe in some PR(including mine) are not included in your pr https://github.com/MoH-Malaysia/covid19-public/pull/159 so maybe put it as a draft PR first then only open a PR when you done merging all the contribution list 
Thanks btw 🙏

**Comment by NobodyButMe-Haiya** [comment]
> @NobodyButMe-Haiya i believe in some PR(including mine) are not included in your pr #159 so maybe put it as a draft PR first then only open a PR when you done merging all the contribution list
> Thanks btw 🙏

are you mean this below ? sorry i'm not sure their new pattern clear 
Cases and Testing

Recovered cases at national and state level
Cases at district level
Cases in cluster at state level
Testing at state level
Number of cases split by variant at country and state level
Granular (anonymised, individual-level) data of confirmed cases:
the date of (suspected) exposure to the virus
the dates of testing and result of RT-PCR
socio-demographic information, e.g. age, sex, ethnicity, comorbidities
clinical stage of COVID-19/severity
Vaccination history of cases (1st and 2nd dose, location, vaccine type)
Breakdown of cases similar to MOH Singapore (example from 26/7/2021)
Locally transmitted cases
Cases linked to previous cases and have already been placed on quarantine
Cases linked to previous cases and were detected through surveillance
Uninked cases
Imported cases
Cases detected upon arrival in Malaysia
Cases who developed the illness during quarantine or isolation
Breakdown by test type (RTK-Ag or RT-PCR)
Total Cases = sporadic + cluster value base on date by district level, state level. If possible township(mukim)
Cases in Category 1-5
Healthcare

1)Active cases by clinical stage

Deaths

Granular (anonymised, individual-level) data on deaths, e.g. age, sex, nationality, comorbidities.
Deaths tabulated by age, sex, and occurrence date
Daily death cases with vaccination history (first&second vaccination appointment, PPV location, vaccine type)
Vaccination

Data on those positive/hospitalised/dead but vaccinated
Vaccinations (partial and full) by age, sex, date and district
Mobility and Contact Tracing

[added] MySejahtera checkins by state
Population age group of MySejahtera check-ins, specified on by-state level
Check-in locations categorized (e.g. supermarkets, hospitals) by state
Tracing total of Inter-state & Intra-state Traveling (Count UniqueUserId vs Two and Above location Unique Check-In between State or Mukim. [Group by State, Mukim]).
Tracing total on location checkin (GroupBy Mukim, GPS location that AREA), travel "intensity" of the area for warn public that mukim with high volume of people travel.

**Comment by chengkangzai** [comment]
i meant the community work list 🤣

**Comment by NobodyButMe-Haiya** [comment]
> i meant the community work list 🤣

sorry dear , if not seen it ..  i assume this https://www.chengkangzai.com/pandemic

**Comment by jlwj51** [comment]
https://github.com/MoH-Malaysia/covid19-public/issues/157#issue-991329603 I also suggest putting it in a table format so its easier to read

Example:
| Link | Description | Created by |
| - | - | - |
| [Google Data Studio Dashboard](https://datastudio.google.com/reporting/8ba8d5d5-9a39-4506-af28-7ab8fcd8f8a9) | An extensive dashboard to be used to monitor the state of the Covid-19 outbreak as well as the progress of vaccination (Malaysia as a whole and by state). Data are manually curated on a daily basis and cross-checked with various official sources for validation and verification purposes. | [aidilsfwn](https://github.com/aidilsfwn) |
| [Google Data Studio Dashboard](https://datastudio.google.com/s/gIQwV1fDCpg) | Positivity Rate Dashboard. | Koh Wyhow |
| [Live site](https://khoohaoyit.github.io/Covid19%20Malaysia%20Heatmap/root.html) | Malaysia Covid 19 Heatmap | [KhooHaoYit](https://github.com/KhooHaoYit/) |
| [Live site](https://www.google.com/) / [GitHub repo](https://www.google.com/) | (example) | [Person 1](https://www.google.com/) and [Person 2](https://www.google.com/) |

**Comment by tnwei** [comment]
Thanks all! Closing this issue as the intended changes have been merged
