### ISSUE TITLE
Data issue: main/epidemic/linelist/linelist_deaths.csv

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#158]
Issues with https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/linelist/linelist_deaths.csv dataset:

1. Assuming _date_ = date the patient passed away and _date_positive_ = date confirmed positive of covid, there are 2536 cases who were confirmed positive after their death (negative days for _date_ - _date_positive_. Of these cases 89 cases were only confirmed positive 30 days after their death. I am not sure whether the data were correct, which I suspect due to wrong data entry.
2. Of these cases, 9 cases have a gap of > 100 days between _date_positive_ to _date_ (i.e. death). I am not sure whether for these cases the data were correctly entered.
3. One case no. 18087 has the date of death in the future (as of the date of this comment on 9/9/2021): _date_ = 2021-09-30 _date_positive_ = 2021-09-01
4. 19 cases received 2nd dose after their deaths.
5. _age_ contains a case equals "10 months". While the rest are numerical data, I think this case can be re-coded as 1 y.o.

Details in the attached file.
[analysis_screen.pdf](https://github.com/MoH-Malaysia/covid19-public/files/7136574/analysis_screen.pdf)

**Comment by MoH-Malaysia** [comment]
Thank you! These were just bugs from pre-processing into the Git push - we've resolved them.

1. Pre-processing error - fixed.
2. Entirely possible if the patient is in hospital for an extended period of time.
3. Typo
4. Pre-processing error - fixed.
5. Fixed to integer.

Many thanks again for the prompt feedback :)

**Comment by moosekaka** [comment]
Hi, just to let you know, _age_ column still contains an entry "6days" .

**Comment by chez1978** [comment]
Thank you for the linelisting! A lot can be done with the data and will
wait for additional linelisting breakdown of positive cases by sex and age
(and vaxtype) to calculate proper death rates. But this is an amazing start
and we can do some modelling already. total deaths with vaccine 1 dose 3532
and 2 dose 1409, totally 4941... it seems most likely because a majority of
elderly population and those in institutions received sinovac so that
affected its numbers.

**Comment by 010111001** [comment]
Please review the following file :

linelist_deaths.csv
- daily total of death does not match with total deaths_malaysia.csv
- got vaccine vaxtype = u, is it UNKNOWN?

deaths_malaysia.csv
- daily total of death does not match with total linelist_deaths.csv
