### ISSUE TITLE
Inconsistent Recovered Cases Count (National)

### ISSUE THREAD

**Issue by DesmondTan757** [MoH-Malaysia/covid19-public#169]
Hi, hope someone could answer my question.
![image](https://user-images.githubusercontent.com/90520218/132954024-15d1b416-eeab-445e-bc13-1b3fe87a7044.png)
I checked data from 24/2/2021 until 8/9/2021 and found that recovered cases count on 26/7/2021 was 9371 in github (9372 in kkm poster) and on 17/8/2021 was 16467 in github (16468 in kkm poster).
I am eager to know which is the correct data. Thanks in advance.

**Comment by MoH-Malaysia** [comment]
This error has been fixed.
