### ISSUE TITLE
Total covid19 patients in icu?

### ISSUE THREAD

**Issue by cikmarrmachang** [MoH-Malaysia/covid19-public#174]
Which column in icu.csv data represent the number of covid19 patients in icu? beds_icu_covid or icu_x?

**Comment by NobodyButMe-Haiya** [comment]
we been asking before because non same with dg or now covidnow portal. we no idea and remove the figure % icu

**Comment by cikmarrmachang** [comment]
> we been asking before because non same with dg or now covidnow portal. we no idea and remove the figure % icu

what do you mean? where did you get data of daily icu usage for covid19 patients?

**Comment by NobodyButMe-Haiya** [comment]
> > we been asking before because non same with dg or now covidnow portal. we no idea and remove the figure % icu
> 
> what do you mean? where did you get data of daily icu usage for covid19 patients?

https://covidnow.moh.gov.my/icu  see active icu  and compare to here datset.

a normal would be 

active icu / bed covid 19 icu * 100 . if we dont get same figure with dg or covidnow, we will not appear the data at https://www.sponline.xyz/kedah.php

data set from icu.csv

**Comment by mnyunus** [comment]
> https://covidnow.moh.gov.my/icu see active icu and compare to here datset.
> 
> a normal would be
> 
> active icu / bed covid 19 icu * 100 . if we dont get same figure with dg or covidnow, we will not appear the data at https://www.sponline.xyz/kedah.php
> 
> data set from icu.csv

The formulae CovidNow uses are: 
Active ICU Patients = icu_covid + icu_pui
ICU Utilisation % = (icu_covid+icu_pui+icu_noncovid)/beds_icu_total

I use same formulae for my dashboard:
https://datastudio.google.com/s/n1w4zvwe0hw

---

**Comment by NobodyButMe-Haiya** [comment]
> > https://covidnow.moh.gov.my/icu see active icu and compare to here datset.
> > a normal would be
> > active icu / bed covid 19 icu * 100 . if we dont get same figure with dg or covidnow, we will not appear the data at https://www.sponline.xyz/kedah.php
> > data set from icu.csv
> 
> The formulae CovidNow uses are:
> Active ICU Patients = icu_covid + icu_pui
> ICU Utilisation % = (icu_covid+icu_pui+icu_noncovid)/beds_icu_total
> 
> I use same formulae for my dashboard:
> https://datastudio.google.com/s/n1w4zvwe0hw

thanks mate, we will check it out tommorow and compare .

**Comment by NobodyButMe-Haiya** [comment]
update.  figure dg sedikit tak same.. akan tengok beberapa hari .. jika sama dengan  covidnow maka baru kami akan update ke portal kami.

**Comment by mnyunus** [comment]
> update. figure dg sedikit tak same.. akan tengok beberapa hari .. jika sama dengan covidnow maka baru kami akan update ke portal kami.

Don't think DG's figures will be same, since his press release at 6.45pm, while Github data (which CovidNow uses) is updated much later, I think midnight.

**Comment by cikmarrmachang** [comment]
> > update. figure dg sedikit tak same.. akan tengok beberapa hari .. jika sama dengan covidnow maka baru kami akan update ke portal kami.
> 
> Don't think DG's figures will be same, since his press release at 6.45pm, while Github data (which CovidNow uses) is updated much later, I think midnight.

thank you very much for the info..really appreciate it

**Comment by cikmarrmachang** [comment]
> update. figure dg sedikit tak same.. akan tengok beberapa hari .. jika sama dengan covidnow maka baru kami akan update ke portal kami.

thank you very much for the info..really appreciate it

**Comment by cikmarrmachang** [comment]
> > https://covidnow.moh.gov.my/icu see active icu and compare to here datset.
> > a normal would be
> > active icu / bed covid 19 icu * 100 . if we dont get same figure with dg or covidnow, we will not appear the data at https://www.sponline.xyz/kedah.php
> > data set from icu.csv
> 
> The formulae CovidNow uses are:
> Active ICU Patients = icu_covid + icu_pui
> ICU Utilisation % = (icu_covid+icu_pui+icu_noncovid)/beds_icu_total
> 
> I use same formulae for my dashboard:
> https://datastudio.google.com/s/n1w4zvwe0hw

is there any data in a form of raw data .csv or .xls for this?
