### ISSUE TITLE
Question about cluster dates

### ISSUE THREAD

**Issue by MyGIS** [MoH-Malaysia/covid19-public#178]
_date_announced: date of declaration as cluster
date_last_onset: most recent date of onset of symptoms for individuals within the cluster. note that this is distinct from the date on which said individual was tested, and the date on which their test result was received; consequently, today's date may not necessarily be present in this column._

Can I assume that "date_last_onset" comes after "_date_announced" ?

**Comment by MoH-Malaysia** [comment]
Not necessarily. For instance, if the last known case had an onset date of 2 days ago, but the cluster was declared today (investigation takes time), then `date_announced` > `date_last_onset`.
