### ISSUE TITLE
Actual death numbers revised to tally with reported death numbers?

### ISSUE THREAD

**Issue by AsyrafRND** [MoH-Malaysia/covid19-public#180]
Are previous daily actual death data revised daily so as to include new daily reported death data? 
I've noticed that the cumulative deaths number between the actual death and reported death had converged on 13th Sept, suggesting that the backlog in reporting had cleared.
As such, one would expect that the actual death number and the reported death number would be similar after 13th Sept.
Yet,  the daily actual death and reported death numbers continue to be different but the cumulative numbers of death are the same.
These are snapshots of the graph of the cumulative death numbers taken on the 14th and the 15th. Notice the difference in cumulative actual death numbers as of 14th Sept:
![IMG_20210916_003923](https://user-images.githubusercontent.com/86554679/133474753-18d7a823-d884-4b18-8de7-70b00aeeb347.jpg)
![IMG_20210916_004147](https://user-images.githubusercontent.com/86554679/133474785-55a08ee8-ab1e-47f2-9a1a-335494270e71.jpg)

**Comment by chez1978** [comment]
I believe there has to be some realistic expectations moving forward as
there will be cases and lags as to actual date of death and determination
that the death is "with" covid-19.

Even in the UK these matters are explained upfront and they have a weekly
window to finalize them. We need to make sure the reporting is properly
aligned to our standard practices. Date of actual death should always be
the same in the death certificate, and causes of death should tally as
well. MOH can use 3, 5 or 7 day revised tallies to avoid similar backlog
building up.

https://www.nuffieldtrust.org.uk/news-item/measuring-mortality-during-covid-19-a-q-a?gclid=Cj0KCQjws4aKBhDPARIsAIWH0JWrt3pYxw2gxC6ty1sdp-otk3SDjQGcyxfqfQPQY9QE7JRq4CM-MiYaAnmPEALw_wcB

Where does this data come from?

When a death occurs, a medical practitioner completes a death certificate
that enables the person’s family to register the death. Death registrations
are collated and the numbers reported by the Office for National Statistics
(ONS) on a weekly basis
<https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/weeklyprovisionalfiguresondeathsregisteredinenglandandwales>
.

There is a time lag between when the death occurred and when the data is
published. For example, data published on 23 March is for registrations
that occurred during the week ending 12 March, with those deaths having
occurred approximately five days prior to registration. Registrations can
be delayed when there is a bank holiday – which we can see in the higher
number of registrations in the weeks following the May and August bank
holidays, and in January, following lower numbers in the previous month.

The death certificate
<https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/877302/guidance-for-doctors-completing-medical-certificates-of-cause-of-death-covid-19.pdf>
will
include the immediate cause of death and the underlying disease or injury
that led up to the death. Contributory causes of death can also be
recorded, where they may have affected the outcome, but illnesses should
not be included on the death certificate if they were present but did not
contribute to the death.

**Comment by chez1978** [comment]
See how CDC does it, we dont have to reinvent the wheel, just need to set a
protocol, announce it and stick to that

https://www.cdc.gov/nchs/nvss/vsrr/covid19/index.htm

**Comment by MoH-Malaysia** [comment]
The numbers are added to the backseries as appropriate.

By construction, the two series should have the same cumulative total.
