### ISSUE TITLE
Request for checkin and checkout(reminders) notifications

### ISSUE THREAD

**Issue by nashlim01** [MoH-Malaysia/covid19-public#183]
I think check-ins and checkouts issues are such a big issue where people always forget about checking out their status or even couldn't find the way to proceed for checking out when there are multiple check-ins.
I think it will make the system more effective to create the notification function with check-in and checkout notify, it will become easier for staff to track the more accurate timeline and also easier for all users to remember about it.

**Comment by MoH-Malaysia** [comment]
We do not take these requests here, unfortunately.
