### ISSUE TITLE
Request for Msia Covid death - by age group, by vaccinated vs unvaccinated, by comorbidities, by NCD (all four displayed into one single bar chart)

### ISSUE THREAD

**Issue by ahbeh** [MoH-Malaysia/covid19-public#185]
Hi, i simply can't find the above Msia covid death data detail breakdown, your help pls. Thank you

**Comment by Stardaus** [comment]
You can find the list here:- [linelist_deaths.csv](https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic/linelist)

Hope it helps.

**Comment by mnyunus** [comment]
I have done something on this, please see:
https://datastudio.google.com/s/onuCTCIqPSQ

**Comment by ahbeh** [comment]
Hi,
Thanks for the feedback.
I have a simplified suggestion : To simplify all  (1)by age group, (2)by vaccinated vs unvaccinated, (3)by comorbidities, (4)by NCD All four information displayed into one single bar chart.
Attached here is a simple version of it for your reference.In order to complete that chart, for each age group, just further breakdown into two bars (V) for fully vaccinated, (N) for not complete/not yet vaccinated.So for 6 group age, total you will have 6x2=12bars.In each individual bar, further breakdown to (i) comorbidities, (ii) single NCD, (iii) none NCD nor comorbidities
Important Note 1: we need to differentiate between comorbidities vs NCD.Because comorbidities = 2 pre-existing diseases exist, while NCD = refer to one/single pre-existing disease only.Comorbidities is more serious than single NCD, hence the risk profiling will be different too.
Important Note 2:the timeline of the displayed duration, although you display the accumulation death case since the beggining of covid back in march 2020, but a more practical/meaningful timeline display will be based on recent cases (which is more represent the delta outbreak).So suggest a daily display (i.e.: Chart title = Total covid death details breakdown for 24th September 2021)or at least on weekly basis (i.e.: Chart title = Total covid death details breakdown for the week of 17th -23rd September 2021)
Here i attach my own sketch version of the ideal chart that described as all the above.With this single chart displayed in the Covid now official webpage on daily or at least weekly basis, even a none highly educated public can esily understand/comprehend the chart within few seconds view of it.this will sure increase the transparency between MOH and malaysian vast public.
Appreciate your further attention and action into this humble suggestion, thank you.
Regards 


    On Thursday, 23 September 2021, 10:45:12 pm GMT+8, mnyunus ***@***.***> wrote:  
 
 


I have done something on this, please see:
https://datastudio.google.com/s/onuCTCIqPSQ

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mnyunus** [comment]
Thanks, but it's just a hobby. Not spending too much time on it.

**Comment by ahbeh** [comment]
This is important for the vast public of Malaysian, as they need to do an informed analyzed decision, for their own health.
For MOH, helping the public to take more responsibility of their preventive health, in return will ease the MOH workload in the long run.
    On Friday, 24 September 2021, 10:49:48 am GMT+8, mnyunus ***@***.***> wrote:  
 
 


Thanks, but it's just a hobby. Not spending too much time on it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrBarbie** [comment]
I have some charts that is a bit more similar to what you are looking for at [Malaysia Deaths visualisation Google Docs](https://bit.ly/2XDhR7s)

I agree with breaking it down into Delta dominant and prior time periods which is what I have. Vaccination may play a role too but our vaccination ramped up at about the same time so I dont think that will provide much more of a different view. This may be worth revisiting when we have platued further with vaccination rates.
What do you mean by NCD? Do you mean NonCommunicableDisease? I dont see the report for this in the data.
With regards to your request for daily/weekly charts I dont think that will be feasible given the way the data updates. Updates on say 24 September doesnt just add deaths from 23 or 24 September its a few days prior which I believe is any new confirmed covid deaths. From what I have seen most will be a few days before like say 20 September with a lower spread both sides.

However if you want some very very specific representations perhaps you can generate your own.

P/S: We cant see the sketch you mentioned.

> Hi, Thanks for the feedback. I have a simplified suggestion : To simplify all  (1)by age group, (2)by vaccinated vs unvaccinated, (3)by comorbidities, (4)by NCD All four information displayed into one single bar chart. Attached here is a simple version of it for your reference.In order to complete that chart, for each age group, just further breakdown into two bars (V) for fully vaccinated, (N) for not complete/not yet vaccinated.So for 6 group age, total you will have 6x2=12bars.In each individual bar, further breakdown to (i) comorbidities, (ii) single NCD, (iii) none NCD nor comorbidities Important Note 1: we need to differentiate between comorbidities vs NCD.Because comorbidities = 2 pre-existing diseases exist, while NCD = refer to one/single pre-existing disease only.Comorbidities is more serious than single NCD, hence the risk profiling will be different too. Important Note 2:the timeline of the displayed duration, although you display the accumulation death case since the beggining of covid back in march 2020, but a more practical/meaningful timeline display will be based on recent cases (which is more represent the delta outbreak).So suggest a daily display (i.e.: Chart title = Total covid death details breakdown for 24th September 2021)or at least on weekly basis (i.e.: Chart title = Total covid death details breakdown for the week of 17th -23rd September 2021) Here i attach my own sketch version of the ideal chart that described as all the above.With this single chart displayed in the Covid now official webpage on daily or at least weekly basis, even a none highly educated public can esily understand/comprehend the chart within few seconds view of it.this will sure increase the transparency between MOH and malaysian vast public. Appreciate your further attention and action into this humble suggestion, thank you. Regards  On Thursday, 23 September 2021, 10:45:12 pm GMT+8, mnyunus ***@***.***> wrote: I have done something on this, please see: https://datastudio.google.com/s/onuCTCIqPSQ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ahbeh** [comment]
Dear MOH,
Thanks for your reply.

I agree with breaking it down into Delta dominant and prior time periods which is what I have. Vaccination may play a role too but our vaccination ramped up at about the same time so I dont think that will provide much more of a different view. This may be worth revisiting when we have platued further with vaccination rates.1. We need to focus on the latest daily/weekly pattern in term of death analysis, only this will make an urgent sense for those public to have a real feel with the latest development of vaccine against current dominant variant. (and hence may push to a higher vaccination rate in Msia)
What do you mean by NCD? Do you mean NonCommunicableDisease? I dont see the report for this in the data. 2. Ya, none communicable disease. The reason for it being: current data only show either has comorbidities (2 diseases) OR no comorbidities (0 disease). But in actual population, there's many with only 1 disease (single NCD), so we have missed up these group of people (which i believe as the case for majority of our population). So for these group of people, they are not able to judge their position using existing insufficient data. Need to close this gap. 

With regards to your request for daily/weekly charts I dont think that will be feasible given the way the data updates. Updates on say 24 September doesnt just add deaths from 23 or 24 September its a few days prior which I believe is any new confirmed covid deaths. From what I have seen most will be a few days before like say 20 September with a lower spread both sides. 3. Pls see my reply in above item 1. If daily not represent the real number, then at least weekly basis will be justify for our real scenario.


However if you want some very very specific representations perhaps you can generate your own.4. I am not good at all in this new IT tool, not even know how to generate simple graph from all this raw data.

P/S: We cant see the sketch you mentioned.5. Is it due to the pencil drawing, or you can't even open that file ? Anyway, here i resketch it into PPT and screenshot for you here (see attachment - this is what i mean with simplified all relevant info into 1 single chart which i am sure will be super easy digested by vast of our Malaysian, include the none highly educated one).

Thank you

Regards,

    On Saturday, 25 September 2021, 01:27:09 am GMT+8, MrBarbie ***@***.***> wrote:  
 
 


I have some charts that is a bit more similar to what you are looking for at Malaysia Deaths visualisation Google Docs

I agree with breaking it down into Delta dominant and prior time periods which is what I have. Vaccination may play a role too but our vaccination ramped up at about the same time so I dont think that will provide much more of a different view. This may be worth revisiting when we have platued further with vaccination rates.
What do you mean by NCD? Do you mean NonCommunicableDisease? I dont see the report for this in the data.
With regards to your request for daily/weekly charts I dont think that will be feasible given the way the data updates. Updates on say 24 September doesnt just add deaths from 23 or 24 September its a few days prior which I believe is any new confirmed covid deaths. From what I have seen most will be a few days before like say 20 September with a lower spread both sides.

However if you want some very very specific representations perhaps you can generate your own.

P/S: We cant see the sketch you mentioned.


Hi, Thanks for the feedback. I have a simplified suggestion : To simplify all  (1)by age group, (2)by vaccinated vs unvaccinated, (3)by comorbidities, (4)by NCD All four information displayed into one single bar chart. Attached here is a simple version of it for your reference.In order to complete that chart, for each age group, just further breakdown into two bars (V) for fully vaccinated, (N) for not complete/not yet vaccinated.So for 6 group age, total you will have 6x2=12bars.In each individual bar, further breakdown to (i) comorbidities, (ii) single NCD, (iii) none NCD nor comorbidities Important Note 1: we need to differentiate between comorbidities vs NCD.Because comorbidities = 2 pre-existing diseases exist, while NCD = refer to one/single pre-existing disease only.Comorbidities is more serious than single NCD, hence the risk profiling will be different too. Important Note 2:the timeline of the displayed duration, although you display the accumulation death case since the beggining of covid back in march 2020, but a more practical/meaningful timeline display will be based on recent cases (which is more represent the delta outbreak).So suggest a daily display (i.e.: Chart title = Total covid death details breakdown for 24th September 2021)or at least on weekly basis (i.e.: Chart title = Total covid death details breakdown for the week of 17th -23rd September 2021) Here i attach my own sketch version of the ideal chart that described as all the above.With this single chart displayed in the Covid now official webpage on daily or at least weekly basis, even a none highly educated public can esily understand/comprehend the chart within few seconds view of it.this will sure increase the transparency between MOH and malaysian vast public. Appreciate your further attention and action into this humble suggestion, thank you. Regards  On Thursday, 23 September 2021, 10:45:12 pm GMT+8, mnyunus @.***> wrote: I have done something on this, please see: https://datastudio.google.com/s/onuCTCIqPSQ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by soleagent** [comment]
> I have some charts that is a bit more similar to what you are looking for at [Malaysia Deaths visualisation Google Docs](https://bit.ly/2XDhR7s)
> 
> I agree with breaking it down into Delta dominant and prior time periods which is what I have. Vaccination may play a role too but our vaccination ramped up at about the same time so I dont think that will provide much more of a different view. This may be worth revisiting when we have platued further with vaccination rates. What do you mean by NCD? Do you mean NonCommunicableDisease? I dont see the report for this in the data. With regards to your request for daily/weekly charts I dont think that will be feasible given the way the data updates. Updates on say 24 September doesnt just add deaths from 23 or 24 September its a few days prior which I believe is any new confirmed covid deaths. From what I have seen most will be a few days before like say 20 September with a lower spread both sides.
> 
> However if you want some very very specific representations perhaps you can generate your own.
> 
> P/S: We cant see the sketch you mentioned.
> 
> > Hi, Thanks for the feedback. I have a simplified suggestion : To simplify all  (1)by age group, (2)by vaccinated vs unvaccinated, (3)by comorbidities, (4)by NCD All four information displayed into one single bar chart. Attached here is a simple version of it for your reference.In order to complete that chart, for each age group, just further breakdown into two bars (V) for fully vaccinated, (N) for not complete/not yet vaccinated.So for 6 group age, total you will have 6x2=12bars.In each individual bar, further breakdown to (i) comorbidities, (ii) single NCD, (iii) none NCD nor comorbidities Important Note 1: we need to differentiate between comorbidities vs NCD.Because comorbidities = 2 pre-existing diseases exist, while NCD = refer to one/single pre-existing disease only.Comorbidities is more serious than single NCD, hence the risk profiling will be different too. Important Note 2:the timeline of the displayed duration, although you display the accumulation death case since the beggining of covid back in march 2020, but a more practical/meaningful timeline display will be based on recent cases (which is more represent the delta outbreak).So suggest a daily display (i.e.: Chart title = Total covid death details breakdown for 24th September 2021)or at least on weekly basis (i.e.: Chart title = Total covid death details breakdown for the week of 17th -23rd September 2021) Here i attach my own sketch version of the ideal chart that described as all the above.With this single chart displayed in the Covid now official webpage on daily or at least weekly basis, even a none highly educated public can esily understand/comprehend the chart within few seconds view of it.this will sure increase the transparency between MOH and malaysian vast public. Appreciate your further attention and action into this humble suggestion, thank you. Regards  On Thursday, 23 September 2021, 10:45:12 pm GMT+8, mnyunus _**@**_.***> wrote: I have done something on this, please see: https://datastudio.google.com/s/onuCTCIqPSQ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Can you get the Numbers of infected for each vaccination brand from time to time? Thanks

**Comment by soleagent** [comment]
> I have some charts that is a bit more similar to what you are looking for at [Malaysia Deaths visualisation Google Docs](https://bit.ly/2XDhR7s)
> 
> I agree with breaking it down into Delta dominant and prior time periods which is what I have. Vaccination may play a role too but our vaccination ramped up at about the same time so I dont think that will provide much more of a different view. This may be worth revisiting when we have platued further with vaccination rates. What do you mean by NCD? Do you mean NonCommunicableDisease? I dont see the report for this in the data. With regards to your request for daily/weekly charts I dont think that will be feasible given the way the data updates. Updates on say 24 September doesnt just add deaths from 23 or 24 September its a few days prior which I believe is any new confirmed covid deaths. From what I have seen most will be a few days before like say 20 September with a lower spread both sides.
> 
> However if you want some very very specific representations perhaps you can generate your own.
> 
> P/S: We cant see the sketch you mentioned.
> 
> > Hi, Thanks for the feedback. I have a simplified suggestion : To simplify all  (1)by age group, (2)by vaccinated vs unvaccinated, (3)by comorbidities, (4)by NCD All four information displayed into one single bar chart. Attached here is a simple version of it for your reference.In order to complete that chart, for each age group, just further breakdown into two bars (V) for fully vaccinated, (N) for not complete/not yet vaccinated.So for 6 group age, total you will have 6x2=12bars.In each individual bar, further breakdown to (i) comorbidities, (ii) single NCD, (iii) none NCD nor comorbidities Important Note 1: we need to differentiate between comorbidities vs NCD.Because comorbidities = 2 pre-existing diseases exist, while NCD = refer to one/single pre-existing disease only.Comorbidities is more serious than single NCD, hence the risk profiling will be different too. Important Note 2:the timeline of the displayed duration, although you display the accumulation death case since the beggining of covid back in march 2020, but a more practical/meaningful timeline display will be based on recent cases (which is more represent the delta outbreak).So suggest a daily display (i.e.: Chart title = Total covid death details breakdown for 24th September 2021)or at least on weekly basis (i.e.: Chart title = Total covid death details breakdown for the week of 17th -23rd September 2021) Here i attach my own sketch version of the ideal chart that described as all the above.With this single chart displayed in the Covid now official webpage on daily or at least weekly basis, even a none highly educated public can esily understand/comprehend the chart within few seconds view of it.this will sure increase the transparency between MOH and malaysian vast public. Appreciate your further attention and action into this humble suggestion, thank you. Regards  On Thursday, 23 September 2021, 10:45:12 pm GMT+8, mnyunus _**@**_.***> wrote: I have done something on this, please see: https://datastudio.google.com/s/onuCTCIqPSQ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Can you continue the chart that showing how many people infected by vaccination brand types and doses from time to time like the info given above  https://bit.ly/2XDhR7s [Malaysia Deaths visualisation Google Docs] ? Thanks
This is very important information to let people know.
