### ISSUE TITLE
Request to Have additional data on the COVID19 Cases - Vaccination Status, Category 

### ISSUE THREAD

**Issue by Stes86** [MoH-Malaysia/covid19-public#186]
May you publish the following information on the new cases reported:
- Vaccination status (No Vaccine, Partial Vaccine and Full Vaccine) 
- COVID19 Category status (Category 1, 2, 3, 4 and 5)
- Which Vaccine used (Pfizer, Sinovac, Astra, Cansino and others if they become available) 

For Hospitalization / ICU
- Average length of stay
- New entry and checkout statistic will be good for analysis 
 
For After Vaccination side effect
- Able to provide the data on this?

**Comment by mnyunus** [comment]
For 3rd item, see the AEFI file:
https://github.com/MoH-Malaysia/covid19-public/tree/main/vaccination

I have done something on AEFI, pls see 2nd tab on:  https://datastudio.google.com/s/pv7ZRaGQSLs

**Comment by Stes86** [comment]
Thank you @mnyunus it is very informative.

**Comment by MoH-Malaysia** [comment]
This data is available at individual level.
