### ISSUE TITLE
Home Quarantine

### ISSUE THREAD

**Issue by teacherumi** [MoH-Malaysia/covid19-public#187]
I have not seen data on home quarantine. Can I simply rule out home quarantine=cases_new-hospitalization-pkrc?TQVM

**Comment by KennethThePro** [comment]
To match https://covidnow.moh.gov.my/ home quarantine numbers as shown below 

![image](https://user-images.githubusercontent.com/86338269/135247134-bdb85abc-c737-4a96-8d80-51d7d54fb9c5.png)

Formula:
Home Quarantine = cases_new - cases_recovered - deaths_new - pkrc_covid - pkrc_pui - hosp_covid - hosp_pui - icu_covid

![image](https://user-images.githubusercontent.com/86338269/135247072-c2da60c7-72d0-4057-a2d9-112b0ff09c67.png)

**Comment by MoH-Malaysia** [comment]
@KennethThePro is right.
