### ISSUE TITLE
sorry 

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#188]
seem  like now all field changing and not inform any of note.

by default , i will take down  my portal statictic since the source keep changing field.

**Comment by MoH-Malaysia** [comment]
Could we know which fields in particular? As much as possible, we've tried to keep naming conventions unchanged.

**Comment by NobodyButMe-Haiya** [comment]
1.  https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/cases_state.csv

Field 3 and Field 4, Revert place without changed.  

2. https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/deaths_state.csv
Bid 4 -  getting weird data only 5 in kedah ?

3. Total Active  cases in kedah as todate 12,536  while covid now - 7,161 . Where's 4k transparency . if 100 +- or  even 500 i accept  but .. 

So my conclusion if this changes if not monitors most of the developer portal and api been made are hire-wire . So better i divert the address to covid now . By Legal matter if figure wrong i have 0 obligation.

**Comment by KennethThePro** [comment]
Issue number 3 is highlighted here, https://github.com/MoH-Malaysia/covid19-public/issues/191#issuecomment-930244134
@MoH-Malaysia would need to address this by explanation or either one of the dataset overrules the rest
