### ISSUE TITLE
age in cases_linelist and death_list contains -1 entries

### ISSUE THREAD

**Issue by moosekaka** [MoH-Malaysia/covid19-public#190]
Please check and correct, cases_linelist contains almost 13,000 -1 age entries and death_linelist contains 366 -1 age entries

**Comment by nicoleyy905** [comment]
Yes noticed the same thing!

**Comment by quyleanh** [comment]
Not only -1, but also 130 age.

**Comment by KohJunLin** [comment]
> 
> 
> Not only -1, but also 130 age.

Regarding one of the 130-year-olds, at least one of them is legitimately 130 years old (as far as we know). The news was reported here: https://www.malaysiakini.com/news/552922

IIRC, what MOH staffers told reporters at the time was that the man was stateless and had no identification documents. So when the next-of-kin claimed he was 130 years old... Well, what can you do but write it down?

**Comment by quyleanh** [comment]
@KohJunLin haha. Ok. I understand now. Thank you for clarifying.

**Comment by moosekaka** [comment]
they already released the linelist for cases. the ages of all positive cases are in there.
https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic/linelist

**Comment by hajime651118** [comment]
Please be informed the minus age records are still there.
Can you please amend those ?
 
Ex. 
2020-01-25,,,,,,,1,0,0,1,2,-1,1,0
...
2020-10-29,,,,,,,0,0,0,12,95,-79,1,1
2020-10-29,,,,,,,0,0,0,12,95,-80,1,1
2020-10-29,,,,,,,0,0,0,12,95,-82,0,1
2020-10-29,,,,,,,0,0,0,12,95,-94,1,1
2020-10-29,,,,,,,0,0,0,12,95,-95,0,1
2020-10-29,,,,,,,0,0,0,12,95,-99,1,1
2020-10-29,,,,,,,0,0,0,12,95,-110,0,1
2020-10-29,,,,,,,0,0,0,12,95,-114,0,1
....

**Comment by MoH-Malaysia** [comment]
-1 indicates missing age.
