### ISSUE TITLE
Data in the Infographics vs Data in the GitHub / COVIDNOW

### ISSUE THREAD

**Issue by SayangiSabah-TimmyLu** [MoH-Malaysia/covid19-public#191]
Dear Administrative,

Would like to clarify which data should we follow or correct?
There are lot of differences data reported by the JKN state itself compare with the date shown in the website COVIDNOW.

You may refer below attached infographics released by JKN Sabah.
![photo_2021-09-26_21-11-40](https://user-images.githubusercontent.com/91001273/134843167-18a16b6a-acd4-48c9-a646-f70139dd85e2.jpg)

compare to the information shown in the website COVIDNOW which i had screenshot.
![asdfasfasf](https://user-images.githubusercontent.com/91001273/134843278-9b819dde-5863-4d50-be52-d64a8f1c6328.png)

I had circled in 'pink' color for these 2 infographics, which are the part where have variance between them.

Your prompt respond is very much appreciated.

Thanks.

**Comment by SayangiSabah-TimmyLu** [comment]
![photo_2021-09-26_21-11-40 - Copy](https://user-images.githubusercontent.com/91001273/134887596-5d17ab9d-47c1-4e82-98f3-7d7c701f9545.jpg)

**Comment by Stes86** [comment]
where do we get the +ICU (New case) and -ICU(discharge case)? this is so confusing to see as it is not informative.

**Comment by NobodyButMe-Haiya** [comment]
kedah jkn active 12536 while covid now 7250 - 390. we also no idea how to explain if people ask  where 4k++ ?

**Comment by KennethThePro** [comment]
Sabah is not the only one with issue, there are a few discrepancy in terms of active numbers (and probably other numbers) between https://covid-19.moh.gov.my/  infographics of most of the states and https://covidnow.moh.gov.my/. The differences ranges from 311 (Perak) to 5175 (Kedah) from the states that provide information of active cases. The compassion is based on 28 September 2021. Data revision overtime is expected so some tolerance level would be accepted but some are in the range of thousands. We would need to know which data shall overrule as the final data if discrepancy occurs.  

Johor
![image](https://user-images.githubusercontent.com/86338269/135284220-8c298574-a350-4a0b-bfd4-a6f18144eb70.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/johor02.jpg)


Kedah
![image](https://user-images.githubusercontent.com/86338269/135284358-a0823aae-2b84-4386-bf7d-e16b926b49e8.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/kedah01.jpg)


Melaka
![image](https://user-images.githubusercontent.com/86338269/135284458-266ea077-f61a-435e-b35e-5834df9d17d4.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/melaka02.jpg)

Pahang
![image](https://user-images.githubusercontent.com/86338269/135284591-ddbb4252-6521-446d-9572-7844cf08257a.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/pahang01.jpg)

Perak
![image](https://user-images.githubusercontent.com/86338269/135284637-73c18676-6dfb-4786-8dc5-3bb594bf9e30.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/perak01.jpg)


Sabah
![image](https://user-images.githubusercontent.com/86338269/135288309-1d1870f2-2244-4f12-8bcb-75f287fb0b14.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/sabah01.jpg)


Selangor
![image](https://user-images.githubusercontent.com/86338269/135284990-4b646cd1-4a94-45da-90df-df705d790037.png)

![](https://covid-19.moh.gov.my/user/pages/03.terkini-negeri/01.2021/09.09/kemaskini-negeri-covid-19-di-malaysia-sehingga-28092021/selangor02.jpg)

**Comment by SayangiSabah-TimmyLu** [comment]
ya i know not just Sabah state, but i pick 1 which lot of discrepancy to hope that if there's someone from the administrative dept or authority to explain why, but i won't be hope high expectation from their reply.  Coz, before CovidNow and GitHub, since last year already have discrepancy.

Below is the 1 of the record i keep track - daily
![28 09 2021](https://user-images.githubusercontent.com/91001273/135305499-93930260-1029-4103-b227-c0b6c576d173.png)

**Comment by MoH-Malaysia** [comment]
Our data comes from the central source - we are not responsible for the dissemination of derived data by 3rd-party sources. 

Sometimes, static infographics may not reflect updated data.
