### ISSUE TITLE
date_announced

### ISSUE THREAD

**Issue by nicoleyy905** [MoH-Malaysia/covid19-public#194]
What is the definition of date_announced? Tried to compute time lag in reporting the death (date_announced - date), there are quite a number of negative numbers (i.e. announced before the person is died?)

**Comment by AsyrafRND** [comment]
I believe there may be some typo error during the data entry, anyway admin should correct it. There are 15 data with the date_announced before the date of death: 
![IMG_20211001_082134](https://user-images.githubusercontent.com/86554679/135547997-b0feafb1-baa4-4c73-b4b4-a94a37056468.jpg)

**Comment by AsyrafRND** [comment]
Also, there may be error in the data which showed more than a year of backlog:
![IMG_20211001_082336](https://user-images.githubusercontent.com/86554679/135548116-d28a8bbd-1e52-45ed-84bf-b2a4dbaa8dc3.jpg)

**Comment by nicoleyy905** [comment]
Thanks @AsyrafRND! I thought I was seeing things

**Comment by mnyunus** [comment]
I just ignored the negatives (which were probably due to entry errors :-) ) and went on doing some charts - for backlog cases see bottom of this site:
https://datastudio.google.com/s/pbKWvx61c0M

**Comment by MrBarbie** [comment]
@mnyunus Out of curiosity, what are you plotting on that graph? Are the days the median of date_announce - date ?
I cant guess what the % number means though.
