### ISSUE TITLE
Death case 30-Sept (197 vs 192)

### ISSUE THREAD

**Issue by SayangiSabah-TimmyLu** [MoH-Malaysia/covid19-public#196]
The actual total for death case both by state and whole malaysia is should be 197 instead of 192 isn't it?
or mistake / typo show in the KKM Youtube?
![asfasfasfas](https://user-images.githubusercontent.com/91001273/135547474-26a06d4b-f9e7-4161-a7e0-d303f8a4e296.png)

**Comment by KennethThePro** [comment]
Looks like using 26335 (192 deaths on 30 September instead of 197) + 121 deaths (1 October) = 26456

![image](https://user-images.githubusercontent.com/86338269/135627390-edbb8270-b066-4e73-abe8-0cb1306ae5ca.png)

**Comment by SayangiSabah-TimmyLu** [comment]
> Looks like using 26335 (192 deaths on 30 September instead of 197) + 121 deaths (1 October) = 26456
> 
> ![image](https://user-images.githubusercontent.com/86338269/135627390-edbb8270-b066-4e73-abe8-0cb1306ae5ca.png)

ya, i also noticed that.
maybe video editor typo the total deaths yesterday.

**Comment by MoH-Malaysia** [comment]
192 is the correct number.
