### ISSUE TITLE
Issue with either date_death or date_announced <Please address soonest possible, admin>

### ISSUE THREAD

**Issue by nicoleyy905** [MoH-Malaysia/covid19-public#199]
As shown below, tried to compute backlog in days but found a number of unreasonable records. Please address the issue soonest possible admin. 
![image](https://user-images.githubusercontent.com/91382115/135780012-c02afb95-c6ee-4f74-8575-7ec12069d749.png)

**Comment by nickkhor** [comment]
![image](https://user-images.githubusercontent.com/22517385/135781348-a2b053ee-cefd-4a4a-ba10-a55b55a0642e.png)

Here are some extra filtered example from "linelist_deaths.csv", as of 4/10/2021

**Comment by MoH-Malaysia** [comment]
Thank you for flagging this! We'll review these records.

**Comment by MoH-Malaysia** [comment]
Sorted!
