### ISSUE TITLE
47 hours in checkin_malaysia_time.csv

### ISSUE THREAD

**Issue by weitheng** [MoH-Malaysia/covid19-public#20]
Why is there in total 47 hours per day in the checkin_malaysia_time.csv?

**Comment by MoH-Malaysia** [comment]
The data is split into half-hour chunks. There are 48 - the chunks are 0-indexed, as is standard in most coding nomenclature. Do review our exhaustive documentation of the variables.

**Comment by weitheng** [comment]
Might wanna include in the documentation that it is split into half-hour chunk?

**Comment by MoH-Malaysia** [comment]
The documentation does contain that detail.
