### ISSUE TITLE
<linelist_deaths.csv> time lag in reporting deaths more than 100 days (Please assist in resolving unreasonable time lag in reporting deaths, Admin)

### ISSUE THREAD

**Issue by nicoleyy905** [MoH-Malaysia/covid19-public#200]
There are in total 96 records have time lag in reporting deaths more than 100 days. Please refer to the snapshot below. Please assist to fix accordingly. 
![image](https://user-images.githubusercontent.com/91382115/135810146-5897c6c6-cebf-407b-84e1-6da7017179eb.png)

**Comment by MoH-Malaysia** [comment]
Most deaths are reported within 7 days, with a median TAT of 3 days or less nationally.
