### ISSUE TITLE
Total number of test vs YB KJ & DG Hisham posted at twitter

### ISSUE THREAD

**Issue by SayangiSabah-TimmyLu** [MoH-Malaysia/covid19-public#203]
How we can get the total test which YB posted at his personal twitter recently 170,933?
![photo_2021-10-05_18-36-49](https://user-images.githubusercontent.com/91001273/136387482-f59d245a-734e-4809-af12-0e3e7f786358.jpg)
![04 10 2021 - 1](https://user-images.githubusercontent.com/91001273/136387654-493eacd3-5e02-4bbe-a7b4-67a6e30221c3.png)

**Comment by RobbiNespu** [comment]
@SayangiSabah-TimmyLu , aku pun rasa heran. At the time data belum publish tapi dah riuh sekampung. yeah.. mereka mmg orang pertama tengok data. Tapi kenapa hebahkan sesuatu yang tidak published dahulu? Where tranparency,, ?

Ugly part, data waktu tu dah beberapa hari tak released
- https://robbinespu.gitlab.io/indieweb/211012055843/

Bila dah released pula, data tak match pula dari apa dia hebahkan hurmm
- https://robbinespu.gitlab.io/indieweb/211017091733/
- https://twitter.com/RobbiNespu/status/1449731414291800073

**Comment by SayangiSabah-TimmyLu** [comment]
> @SayangiSabah-TimmyLu , aku pun rasa heran. Happen a lot lately, For example..
> 
> * https://twitter.com/Khairykj/status/1447829559206760450
> 
> At the time data belum publish tapi dah riuh sekampung. yeah.. mereka mmg orang pertama tengok data. Tapi kenapa hebahkan sesuatu yang tidak published dahulu? Where tranparency,, ?
> 
> Ugly part, data waktu tu dah beberapa hari tak released
> 
> * https://robbinespu.gitlab.io/indieweb/211012055843/
> 
> Bila dah released pula, data tak match pula dari apa dia hebahkan hurmm
> 
> * https://robbinespu.gitlab.io/indieweb/211017091733/
> * https://twitter.com/RobbiNespu/status/1449731414291800073

![photo_2021-10-15_07-25-40](https://user-images.githubusercontent.com/91001273/137656642-31ccfc44-92ea-42b0-9ad1-b56e415addc7.jpg)
your above link is refers to covid cases for 12th October, so the jumlah saringan sepatutnya rujuk sehingga covidnow kemaskini saringan sehingga 12hb Oktober.

manakala untuk kadar peratusan yang dipaparkan di covidnow adalah PURATA kadar peratusan bagi tempoh 7 hari yang terdekat, bukan sehari.  

Jikalau mahu dapatkan kadar peratusan pada hari tersebut (12hb Oktober), maka sendiri buat pengiraan matematik asas.
Kes positif 7,276 bahagi jumlah saringan 148,346 yang telah memperolehi keputusan daripada makmal = 4.90%.

*keputusan saringan tidak sama dengan saringan yang diambil.
**saringan yang telah diambil memerlukan masa. RTK = 1 hari, PCR = beberapa hari kemudian

**Comment by RobbiNespu** [comment]
Not that point, the point is no data released when KJ and DG speak (or brag) about it aka this issue #203 titled

> Jikalau mahu dapatkan kadar peratusan pada hari tersebut (12hb Oktober), maka sendiri buat pengiraan matematik asas.
Kes positif 7,276 bahagi jumlah saringan 148,346 yang telah memperolehi keputusan daripada makmal = 4.90%.

then you not even read the link i give. the link also include the calculation. 

nevermind even your screenshot is newer not like this this issue #203 concern about

**Comment by SayangiSabah-TimmyLu** [comment]
> Not that point, the point is no data released when KJ and DG speak (or brag) about it aka this issue #203 titled
> 
> > Jikalau mahu dapatkan kadar peratusan pada hari tersebut (12hb Oktober), maka sendiri buat pengiraan matematik asas.
> > Kes positif 7,276 bahagi jumlah saringan 148,346 yang telah memperolehi keputusan daripada makmal = 4.90%.
> 
> then you not even read the link i give. the link also include the calculation.
> 
> nevermind even your screenshot is newer not like this this issue #203 concern about

below here is for 5th October, which as exactly tally to Covidnow calculation.
![05 10 2021](https://user-images.githubusercontent.com/91001273/137758902-10597b69-3b7f-4511-ab49-6992fa963549.png)

while below this is for 12th October, which also tally to Covidnow calculation.
![12 10 2021](https://user-images.githubusercontent.com/91001273/137759200-99ff53e7-7b00-49f1-8000-1ae9a1740af7.png)

**Comment by SayangiSabah-TimmyLu** [comment]
![photo_2021-10-19_14-16-19](https://user-images.githubusercontent.com/91001273/137858406-38288acc-dcfa-4fdf-8106-f64c3935fc33.jpg)
![16 10 2021](https://user-images.githubusercontent.com/91001273/137858422-882bf1f8-d1d2-4501-86cc-480953a885a4.png)
