### ISSUE TITLE
Suggestion - to put a remark that data as of test date updated.

### ISSUE THREAD

**Issue by SayangiSabah-TimmyLu** [MoH-Malaysia/covid19-public#209]
![2](https://user-images.githubusercontent.com/91001273/138386402-e39f8da7-e857-4933-a6a7-67583cb0819a.png)
![1](https://user-images.githubusercontent.com/91001273/138386416-3a6fa87a-8cb2-4e78-bfc5-98fd949d24c6.png)

**Comment by MoH-Malaysia** [comment]
Tradeoff between parsimony and thoroughness.
