### ISSUE TITLE
Issues with cases line list data sets

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#214]
Thank you for the line listing data for cases, which goes along with the spirit of transparency in research and data sharing.

However, there are several issues with regards to the variables contained in the datasets:
- may add outcome of the cases, i.e. recovered/death. This variable is crucial to fully utilize the datasets and gain more clinical insights.
- age contains -1, which I suppose might be intended either for age < 1 y.o or missing value? If it was intended to be missing value, I would suggest that the value should be an empty string. Else, this should be documented in the README.md
- the missing district is denoted as -1 (i.e. in reference to param_geo.csv). In this case, I would suggest that the value should be an empty string.

Best regards.

**Comment by chez1978** [comment]
It would be ideal if a unique id linking the case and death records

**Comment by MoH-Malaysia** [comment]
We will generate unique links between cases and deaths in revisions to the [linelists](https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic/linelist).
