### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#221]
https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/clusters.csv

long time not view , seem the data not maintain properly. hmm sadly

**Comment by m0ses1** [comment]
What do you mean by the data is not maintained properly? If you mean the data is improperly structured, GitHub says that  "We can't make this file beautiful and searchable because it's too large."

**Comment by NobodyButMe-Haiya** [comment]
> What do you mean by the data is not maintained properly? If you mean the data is improperly structured, GitHub says that "We can't make this file beautiful and searchable because it's too large."

i check back my website and no output  so i check back the order of field previous and current 
"
KLUSTER DTI BUKIT JALIL,"5,10,14","CHERAS, KEPONG & PORT DICKSON"
Old days supposed to be 
"
KLUSTER DTI BUKIT JALIL,"CHERAS, KEPONG & PORT DICKSON"

The pattern should be. cluster name | state | district

**Comment by KennethThePro** [comment]
On 2nd November 2021, they changed the string of all the states into idxs. You will have to refer to the [param_geo.csv](https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/linelist/param_geo.csv) file to pair the state to the idxs

Commit Hash on the Changes: https://github.com/MoH-Malaysia/covid19-public/commit/904f7412fa2349fbde99f11a5d44e077a5aa08ca

**Comment by NobodyButMe-Haiya** [comment]
> On 2nd November 2021, they changed the string of all the states into idxs. You will have to refer to the [param_geo.csv](https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/linelist/param_geo.csv) file to pair the state to the idxs
> 
> Commit Hash on the Changes: [904f741](https://github.com/MoH-Malaysia/covid19-public/commit/904f7412fa2349fbde99f11a5d44e077a5aa08ca)

thanks with information . i will close this  even thou quite odd with their decision .
