### ISSUE TITLE
Negative values in cases_pvax in cases_malaysia and cases_state

### ISSUE THREAD

**Issue by KennethThePro** [MoH-Malaysia/covid19-public#222]
There are a lot of negative values in the column `cases_pvax` since 1st September 2021 in the cases_malaysia file and since 21st April 2021 in the cases_state file. So far the negative values just seem to be there to ensure the total number of cases are equal but hopefully this will be resolved

**Comment by sharuzzaman** [comment]
How can cases for partial vax become negative? Partial vax suddenly become unvax since 1 September?

**Comment by KennethThePro** [comment]
Issue of negative values fixed with 734c7c79aaae55d26e9011626a9e9c0517511c62. Issue is closed
