### ISSUE TITLE
Data on measures taken for early treatment

### ISSUE THREAD

**Issue by jstumpin** [MoH-Malaysia/covid19-public#225]
In keeping with WHO's recent [advice](https://youtu.be/uGCK8Z27xd0?t=78), "_vaccines **and**, not vaccines **or**_", together with Japan's dramatic downtick of Covid-19 cases (linked here: https://youtu.be/E1GF0H9V_1g), when are we going to have such data released?

The trend based on vaccinated vs. unvaccinated is fast becoming obsolete, given the [status quo](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&uniformYAxis=0&pickerSort=asc&pickerMetric=location&Metric=Vaccine+doses+and+confirmed+deaths&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=MYS~IND~JPN~SGP~IDN). Adding early treatment data would give finer granularity, in turn providing better assessment.

**Comment by jstumpin** [comment]
Any homegrown study on these treatments: https://c19early.com ?

**Comment by MoH-Malaysia** [comment]
Apologies - this is beyond the scope of our data at present.
