### ISSUE TITLE
anyone can make a chart that showing how many people infected by vaccination brand types and doses from time to time?

### ISSUE THREAD

**Issue by soleagent** [MoH-Malaysia/covid19-public#226]

**Comment by ariffrahimin** [comment]
Since there is no data in vaccine brand correlated with how many people are infected, it is impossible to chart it. But there is data that is correlate vaccine doses with how many people are infected.

**Comment by MoH-Malaysia** [comment]
All data on breakthrough infection is provided at individual-level in the cases linelist.
