### ISSUE TITLE
Request for cases by category 1,2,3,4,5

### ISSUE THREAD

**Issue by MaisarahPauzi** [MoH-Malaysia/covid19-public#234]
Please include data of the new cases with category 1,2,3,4,5.

**Comment by azimanabdullah** [comment]
It will be great if for each category, there are breaking into cases_unvax, cases_pvax, cases_fvax, cases_boost, cases_0_4	cases_5_11, cases_12_17, cases_18_29, cases_30_39, cases_40_49, cases_50_59, cases_60_69, cases_70_79 and cases_80.

It should help everybody to see the insight into how significant the vaccine is according to age group on the level of severity of new cases (category 1 - 5).

**Comment by MoH-Malaysia** [comment]
This data may be misleading for its purpose, because it tracks the category of the case upon registration only.
