### ISSUE TITLE
Population data does not add up

### ISSUE THREAD

**Issue by chiacy** [MoH-Malaysia/covid19-public#235]
I have tabulated the population data in order to get percentage of population segments, i.e. pop_18 over pop, etc

I noticed that the figures does not add up when I try to sum all pop_* columns which should be the same as pop column

example as attached image

Can someone check if I am getting the calculation wrong?

thanks in advance

<img width="1148" alt="Screenshot 2022-02-16 at 1 14 06 AM" src="https://user-images.githubusercontent.com/7408097/154114103-6d883be8-bd05-48c9-9961-394959aef0c5.png">

**Comment by MoH-Malaysia** [comment]
It is not intended to sum.

`pop`: All people
`pop_18`: All people 18+ (including 60+)
`pop_60`: All people 60+
`pop_12`: All people 12-17
`pop_5`: All people 5-12

We agree this is our fault - we will improve the documentation for the population file.
