### ISSUE TITLE
Documentation for static data

### ISSUE THREAD

**Issue by tengku-hanis** [MoH-Malaysia/covid19-public#236]
Hi, can you please add clear documentation for static data (population.csv)? 
I noticed for pop_18 and pop_60, it means 18 and above and 60 and above. But, pop_5 means 5 and below. 
What are the other population estimates mean? Like for pop_12. Does it mean 12-18 or 5-12? 
Thanks.

**Comment by MoH-Malaysia** [comment]
Agreed - we will add documentation.
