### ISSUE TITLE
Request for Markov State Changes for infected

### ISSUE THREAD

**Issue by Hezaika** [MoH-Malaysia/covid19-public#239]
Would be insightful to have markov state change probability for those who are in quarantine and in markov state of :

1. Kuarantin di Rumah
2. PKRC
3. Hospital
4. ICU (tidak perlu ABP)
5. ICU (perlu ABP) 

This would enable potential forecasting for worsening of infected symptom. 
(would be better if could be given term of what type of vaccine/treatment they received)

**Comment by MoH-Malaysia** [comment]
Completely understand the rationale behind the request, but without a full EMR system, this is unfeasible as of now.
