### ISSUE TITLE
All-Cause Mortality data

### ISSUE THREAD

**Issue by akarlinsky** [MoH-Malaysia/covid19-public#24]
Great initiative!

Could you also provide deaths from all causes (not just COVID) by day/week/month?

**Comment by MoH-Malaysia** [comment]
Could you make a pull request to add to the [data wishlist](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests), please? However, do bear in mind that this is much broader work which we're not looking to provide at the moment.
