### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by dna33** [MoH-Malaysia/covid19-public#240]
Hi all, congratulations on the great work with this Github! Both to the team maintaining it and to its user base for keeping it alive.

I worked to implement and operate the Chilean covid19 GitHub in https://github.com/MinCiencia/Datos-COVID19/ and after reading  [this comment in Nature journal](https://www.nature.com/articles/d41586-022-00424-9) by @edomt I felt the need to contact you to see if we can create something together. 

Any ideas?

**Comment by MoH-Malaysia** [comment]
Hi! Someone from our team will contact you this week. :)
