### ISSUE TITLE
[Request] Vaccination data for Orang Asli

### ISSUE THREAD

**Issue by ZuAJ** [MoH-Malaysia/covid19-public#243]
Hi. I need to analize and update on vaccination among orang asli weekly based on district level and type of vaccine received.
Variable needed:

1. Date
2. partial vaccination - adult (=>18 years old)
3. full vaccination - adult (=>18 years old)
4. partial vaccination - teenager
5. full vaccination - teenager
6. partial vaccination - children
7. full vaccination - children
8. booster

here are example of the excel form data

![image](https://user-images.githubusercontent.com/102500767/160326267-b9d4eafb-4853-4097-af1d-91024ab921bc.png)

Making these data available will really helpful by reducing workload for my staffs in clinic and district level. Thank you

**Comment by MoH-Malaysia** [comment]
As of now, we provide data on OA vaccination in the [`vax_demog_ethnicity.csv`](https://github.com/MoH-Malaysia/covid19-public/blob/main/vaccination/vax_demog_ethnicity.csv) file, but we don't have a breakdown by multiple variables.

We will look into providing raw underlying data to assist with your use case.
