### ISSUE TITLE
Death by Age

### ISSUE THREAD

**Issue by Harjeet61** [MoH-Malaysia/covid19-public#247]
Death by Age don't add up to total deaths.
![image](https://user-images.githubusercontent.com/88190542/169680215-3bde4fe7-b58f-4115-a18e-9a1c3d939e6b.png)

**Comment by MoH-Malaysia** [comment]
The data covers the most recent 24 weeks - it's not meant to add up.

Individual-level deaths are available - you can tabulate the data in any way you prefer from there.
