### ISSUE TITLE
Demographic breakdown?

### ISSUE THREAD

**Issue by timriffe** [MoH-Malaysia/covid19-public#25]
Excellent initiative, many thanks for posting this data. I wonder if it would be possible to offer tabulations of cases, deaths, tests, and vaccinations by age groups and sex breakdowns? This would be valuable information for making international comparisons.
Many thanks,
Tim Riffe

**Comment by MoH-Malaysia** [comment]
Could you make a pull request to add to the [data wishlist](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests), please?
