### ISSUE TITLE
icu_covid subset of hosp_covid?

### ISSUE THREAD

**Issue by fhepi** [MoH-Malaysia/covid19-public#252]
Dear All, 

I would kindly like to ask the following two questions: 

1) is the variable "vent_x" (ICU dataset) only referring to patients in category x ventilated in ICU or does it also include patients in category x outside of ICU?
2) is the number of "icu_x" (ICU dataset) a subset of the number in variable  "hosp_x"? I.e. will for example 10 covid patients in ICU be included in the number of covid patients in hospital are are these variables treated separately?

Thank you very much for clarification!

**Comment by MoH-Malaysia** [comment]
1) `vent_x` is a subset of `icu_x`

2) `icu_x` is not a subset of `hosp_x`
