### ISSUE TITLE
In cases_state.csv, there're two -ve values

### ISSUE THREAD

**Issue by mildredve** [MoH-Malaysia/covid19-public#26]
Thanks for the data! would love to know if the negative values in cases_state.csv is real?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MILDRE~1.EPU/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MILDRE~1.EPU/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

date | state | cases_new
-- | -- | --
1/8/2021 | W.P. Kuala Lumpur | -101
5/19/2020 | W.P. Putrajaya | -1

</body>

</html>

![image](https://user-images.githubusercontent.com/61527465/126861702-090bc3ce-31bc-491f-bdd8-24faf79181de.png)

**Comment by MoH-Malaysia** [comment]
Thanks for flagging! We'll check on this and reopen - may have been due to data revisions, particularly on the _location_ of the case.
