### ISSUE TITLE
Positive cases for state level(Selangor)year 2021,need my data for claiming mySalam.

### ISSUE THREAD

**Issue by Jxx-9x** [MoH-Malaysia/covid19-public#262]
Helo my name is Jesli Jouti,I need my data about when I got Covid and approvement about my Quarantine for 14 days,like (HSO) or maybe a date,I really need it for provenance,thnk u.
Please email me: aqbhnie99@gmail.com

**Comment by MoH-Malaysia** [comment]
This is outside the scope of open data.
