### ISSUE TITLE
checkin_malaysia_time.csv column unit

### ISSUE THREAD

**Issue by takheru** [MoH-Malaysia/covid19-public#27]
Dear author,

I have checked the file for checkin_malaysia_time.csv. Please state the unit for the column, it had 47 columns, does it mean it recorded the number of check ins for every 30 minutes?

Cheers,
Boo

**Comment by chonggs** [comment]
Actually there are 48 columns. And yes, the buckets are every 30 minutes. As clarified here: https://github.com/MoH-Malaysia/covid19-public/issues/20
