### ISSUE TITLE
![image](https://user-images.githubusercontent.com/117550441/214703911-c287dff8-5348-4ed5-8b83-c63168c7f7be.png)

### ISSUE THREAD

**Issue by agnihl** [MoH-Malaysia/covid19-public#270]
![image](https://user-images.githubusercontent.com/117550441/214703911-c287dff8-5348-4ed5-8b83-c63168c7f7be.png)

The linelist of case and death in S3(.parquet) latest update was on Oct 2022. However linelist in github(.csv) latest update was on Jan 2023. Both are not in sync.

_Originally posted by @drmayu7 in https://github.com/MoH-Malaysia/covid19-public/issues/260#issuecomment-1404302921_

**Comment by MoH-Malaysia** [comment]
Fixed.
