### ISSUE TITLE
Tests counts being reported for days in the future 

### ISSUE THREAD

**Issue by philip-khor** [MoH-Malaysia/covid19-public#272]
From commit c53084c onwards, tests counts in [epidemic/tests_state.csv](https://github.com/MoH-Malaysia/covid19-public/commit/6146e1f053ccbc940d46e0b33abe2618ff69c7bf#diff-cc308a864b86386d50ba376016757a398001962ed03aaa55b885801ca695b339) and [epidemic/tests_malaysia.csv](https://github.com/MoH-Malaysia/covid19-public/commit/6146e1f053ccbc940d46e0b33abe2618ff69c7bf#diff-5bb22b1a3372e858963a84e964f92f89b062e7b6273489be7f6289453acc49f9) are being generated for future dates up till December 2024.

**Comment by MoH-Malaysia** [comment]
Fixed: https://github.com/MoH-Malaysia/covid19-public/blob/main/epidemic/tests_malaysia.csv

**Comment by philip-khor** [comment]
Seems to be happening again in https://github.com/MoH-Malaysia/covid19-public/commit/f73863ce41cca01cb6cc7d95b90be6564b5bf9af
