### ISSUE TITLE
Request daily positive by age

### ISSUE THREAD

**Issue by takheru** [MoH-Malaysia/covid19-public#28]
Dear author,
Great data. May we request data for daily positive broken down by age or age group?
This will be crucial or important to check the age composition and find how to protect each age group based on activites.

Best

**Comment by MoH-Malaysia** [comment]
Could you make a pull request to add to the [data wishlist](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests), please?
