### ISSUE TITLE
Corrupted/missing data in Mysejahtera 27-31 May?

### ISSUE THREAD

**Issue by chonggs** [MoH-Malaysia/covid19-public#29]
For `checkin_malaysia_time.csv` date range 2021-05-27 to 2021-05-31 the numbers are illogically low (bucket 20 or 10:00am onwards). Doesn't seem to be app/server issue, as the numbers are back to normal again at 00:00 each next day.

![mysj-bucket-20210527](https://user-images.githubusercontent.com/6513410/126864746-1fb7c02a-9797-419c-aa9b-561430079191.png)

**Comment by MoH-Malaysia** [comment]
Thanks for flagging! We'll check and revert once we've diagnosed.

**Comment by chonggs** [comment]
Some further findings: These highlighted numbers on 2021-05-31 are the Top 1-7 highest values in the whole dataset. To have them back-to-back like that, most likely there is some data corruption going on here. @MoH-Malaysia 

![mysj-bucket-20210527-max](https://user-images.githubusercontent.com/6513410/126871962-2ca78d5a-ca3e-4b1e-b323-bfc8eaae89f0.png)
