### ISSUE TITLE
Incorrect data on 16/3/2020

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#3]
For state data on 16/3/2020, "covid19-public/epidemic/cases_state.csv", line number 2:16, the number marked as new cases are not new cases. These are cumulative cases, and by right left blank/NA.

The same goes to national data on 16/3/2020,  "covid19-public/epidemic/cases_malaysia.csv", line 2, the reported new cases on the date is supposed to be 125, not 553, which is actually the cumulative cases by 16/3/2020.

**Comment by MoH-Malaysia** [comment]
Amended documentation accordingly. Thank you.
