### ISSUE TITLE
Daily testing at state level

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#4]
As of now, the daily testing data is given at national level "covid19-public/epidemic/tests_malaysia.csv". If possible, the data is also given at state level. This allows analysis of positivity rate by state.

**Comment by yekit24** [comment]
This is really needed ! Because we can know every state situation

**Comment by MoH-Malaysia** [comment]
We have collated your request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md). Thank you for your input!
