### ISSUE TITLE
Clarification on the definition for population.csv dataset

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#40]
Need clarification on the column **pop_18**, the documentation mention 18+. Does this mean all aged ≥ 18 y.o. including ≥ 60 y.o. (60+)? Or only those aged between 18+ to 60+? Maybe can change the notation to use ≥ symbol be more descriptive.

**Comment by MoH-Malaysia** [comment]
18 and above, 60 and above respectively - we'll make a change noting that!
