### ISSUE TITLE
checkin_malaysia_time.csv outliers, potentially aggregation issue

### ISSUE THREAD

**Issue by lejarx** [MoH-Malaysia/covid19-public#48]
Hi, 

For (checkin_malaysia_time.csv), is there any issue with the data count on the following time-density date

Day 31st May 2021, time density 15 until 21. The precendent and subsequent counts from this time are also strangely low.
I was suspecting that the aggregation wasn't correct around.

Thanks

![image](https://user-images.githubusercontent.com/6431985/126925885-d9b90b70-24e4-407d-a14b-400eae071933.png)

![image](https://user-images.githubusercontent.com/6431985/126925787-96498c84-0b32-4bea-90c0-dc8f1a21dfdf.png)

**Comment by MoH-Malaysia** [comment]
Cool visual! Yep, we're aware of this issue - someone flagged it previously. For transparency's sake, we'll leave it up until we revise the series.

**Comment by lejarx** [comment]
Ah, noted.

I just browsed through the previously closed issues. Maybe to avoid duplication of issues, you may want to leave it opened until it's really solved? 

Thanks for making this data available. Awesome work

**Comment by chonggs** [comment]
@lejarx Yup, spotted & reported it here: #29 
Agreeing with you that unresolved issues should be left Open.
