### ISSUE TITLE
Discrepancy in count icu.csv and press release

### ISSUE THREAD

**Issue by wnarifin** [MoH-Malaysia/covid19-public#55]
There are discrepancies between the total number of covid patient in ICU and under ventilation support calculated from the icu.csv and the ones reported in the press release (https://kpkesihatan.com).

For example, on 24/7/21, the sum for **icu_covid** column and **vent_covid** are 1397 and 799 respectively, while the number reported (https://kpkesihatan.com/2021/07/24/kenyataan-akhbar-kpk-24-julai-2021-situasi-semasa-jangkitan-penyakit-coronavirus-2019-covid-19-di-malaysia/) were 950 and 468 respectively.

**Comment by MoH-Malaysia** [comment]
The press release explicit states that the data is correct as of noon. Our documentation details that healthcare data is correct as of 2359.
