### ISSUE TITLE
checkin_malaysia.csv checkins column does not tally with checkin_time.csv sum of rows

### ISSUE THREAD

**Issue by mildredve** [MoH-Malaysia/covid19-public#59]
![image](https://user-images.githubusercontent.com/61527465/127076189-84437508-4e0b-4636-a101-342476d85b09.png)
Hello Team, 
I was checking through whether the checkins column in checkin_malaysia.csv is equal to the sum of rows in checkin_time.csv. 
These dates came up with differences. Appreciate your confirmation.

**Comment by mildredve** [comment]
Further clarification:
checkin_malaysia_time.csv, I got the total checkins for each date
![image](https://user-images.githubusercontent.com/61527465/127239900-8208b5f8-9a4c-4a59-bf68-eb7fc6e02abd.png)

I compared it to checkin column (B) in  checkin_malaysia.csv. The dates in the previous post are the ones that do not match.

**Comment by MoH-Malaysia** [comment]
Thanks for flagging! Problem solved.
