### ISSUE TITLE
Efficacy of vaccine in Malaysia in preventing transmission

### ISSUE THREAD

**Issue by DrNMA** [MoH-Malaysia/covid19-public#64]
Data to look for:
-Vaccination status (1st and 2nd dose)
-Case positive of the vaxxer
-Case positive of closed contacts

**Comment by DrNMA** [comment]
Source: mysejahtera

**Comment by MoH-Malaysia** [comment]
Please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
