### ISSUE TITLE
Covid19 Disease Category in Daily Covid19 Cases

### ISSUE THREAD

**Issue by umaurosli** [MoH-Malaysia/covid19-public#65]
Can  you include data of daily cases based on categories of Covid19 
 disease just like this KKM graphics? Its also very nice if this data can be specific by states also, so that everyone can see 
 deeply on Covid19 disease effecting us. (https://www.facebook.com/kementeriankesihatanmalaysia/photos/a.390879946236/10158074729016237/)

**Comment by MoH-Malaysia** [comment]
Please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
