### ISSUE TITLE
Clarification needed: are reported positive cases from RT-PCR results alone

### ISSUE THREAD

**Issue by ming86** [MoH-Malaysia/covid19-public#74]
Hello, 

I understand that RT-PCR is the gold standard for COVID-19 testing, those tested positive on RTK-Ag will be confirm again with RT-PCR testing. 

https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic

Are daily reported positive cases from RT-PCR results alone? or is it includes RTK-Ag results ?

**Comment by MoH-Malaysia** [comment]
Both.

**Comment by ming86** [comment]
> Both.

Thanks for prompt reply. 
 
I know some tested positive on RTK-Ag, can be false positive after tested with RT-PCR.

So, will there any adjustment to the data when those RTK-Ag tested positive, but RT-PCR tested negative?

**Comment by dogecoin-moh** [comment]
> Both.

Really? I thought only RT-PCR with Detected result will count as a Covid Positive Case.
