### ISSUE TITLE
Clarification on total vaccination registration & total population dataset

### ISSUE THREAD

**Issue by agnes-lyy** [MoH-Malaysia/covid19-public#75]
Hello MoH, I would like to clarify the numbers of total registered vaccination (vaxreg_state.csv) & numbers of total population (population.csv). The reason being is that in some dates & states, the former exceeds the latter

For example, on 23rd July 2021, total number of registered vaccination for W.P. Kuala Lumpur is 1,830,956. While the total population of W.P. Kuala Lumpur is 1,773,700

Can I know the reason of total number of registered vaccination being higher than total number of population? Based on README.md provided, it seems like total is calculated based on number of unique registrants

Thank you!

**Comment by MoH-Malaysia** [comment]
This is more of a question for the CITF, but broadly, there are 3 reasons:

1. Undocumented residents are not included in DOSM's population estimates, but can nevertheless register for vaccination via any one of the multiple channels.
2. DOSM's population estimates are based on location of residence, but many may register to take the vaccine where they work. This may especially affect the greater Klang Valley, where inter-territorial mobility is high (both KL and Putrajaya are enclaved within Selangor).
3. DOSM's population estimates _may_ require refreshing (however, note that 1 and 2 would still hold even if the estimates were updated). This is not unique to DOSM - countries everywhere have struggled to conduct robust censuses during the pandemic.

As such, we recommend you look at Selangor + KL + Putrajaya as a single unit.

Hope this clarifies!

**Comment by agnes-lyy** [comment]
Thank you for the swift reply!
