### ISSUE TITLE
Test Cases not being updated for the past 2 days

### ISSUE THREAD

**Issue by yoonwaiyan** [MoH-Malaysia/covid19-public#78]
Hi, just wondering is it intentional that the test cases isn't being updated for the past 2 days? I'm doing a graph about it and just realized it's not being updated recently. Is there any change of test cases being planned or the update being halted?

**Comment by amirmazmi** [comment]
It is not even one week....

**Comment by yoonwaiyan** [comment]
I'm not sure your intention behind this statement, I'm only curious and not blaming. I observed that other stats are being updated but the test cases are not. 

With many data requests coming in, my only guess is that there are works to do for updating the data being displayed, which I appreciate.

**Comment by amirmazmi** [comment]
@yoonwaiyan nothing against you here. 
Just having a hard time understanding why the data in this repo is not updated. Definitely not expecting updates on the dot but some data are only available as far back as 26th. Allocated some resources to work on this but having second thoughts. 

Anyway, thank you and everyone else for your effort in spending time looking into the data.

**Comment by idcmsbeta** [comment]
maybe you can used the clusters.csv for total test cases? the problem we see here symptomatic vs cluster. so better base on cluster

**Comment by MoH-Malaysia** [comment]
Thank you everyone for flagging this - in the spirit of openness, we will not close this issue. 

We are working hard to improve the granularity and breadth of the data in this repo - please stay tuned. Part of the reason for the delays are cron failures as we re-work and update our pipelines to have more granularity.

Thank you again for your comments and for pushing us to do better. We're committed to this.

**Comment by chonggs** [comment]
Thank you @MoH-Malaysia for making these data available. We may be a bit late in comparison to other countries, but everything will have a starting point. Keep up the good work! 🙂

**Comment by yoonwaiyan** [comment]
@NobodyButMe-Haiya, that's one valid perspective of looking into it but my current perspective of looking into it is the overall positivity rate - which I can definitely see the possibility of the data being segregated by the states to provide an even better overview of the severity of Covid cases in Malaysia.

@MoH-Malaysia thanks for the update and the hard work to get the data updated!

**Comment by NobodyButMe-Haiya** [comment]
> @NobodyButMe-Haiya, that's one valid perspective of looking into it but my current perspective of looking into it is the overall positivity rate - which I can definitely see the possibility of the data being segregated by the states to provide an even better overview of the severity of Covid cases in Malaysia.
> 
> @MoH-Malaysia thanks for the update and the hard work to get the data updated!

you mean prefer as not raw data ? or aggregate value by state.  Via SQL is much easier using crontab while my sample using only PHP filtered kuala muda only . A drill down  sum state to district to  not sure where mukim call would be fantastic. 
For me , if i crontab and push to another db again quite hassle and better grab data as it.

**Comment by yoonwaiyan** [comment]
I mean aggregate value by state. I'm not sure how the data is structured before exporting to this CSV, there are many ways this could be done, even better if there's a Hadoop cluster to store data and do a map reduce export. I agree that drilling down to districts would be even greater, maybe by postal codes, though it depends on how the data, tests, cases or clusters wise, are recorded. This is worth mentioning as a data request in contrib.md too.

**Comment by amirmazmi** [comment]
Yes I agree, even if was at PKD level would be a lot more useful, especially for deriving value out of mobility data. Then people would be able to start looking at modelling the data.

**Comment by MoH-Malaysia** [comment]
Updated.

**Comment by chiacy** [comment]
> Thank you everyone for flagging this - in the spirit of openness, we will not close this issue.
> 
> We are working hard to improve the granularity and breadth of the data in this repo - please stay tuned. Part of the reason for the delays are cron failures as we re-work and update our pipelines to have more granularity.
> 
> Thank you again for your comments and for pushing us to do better. We're committed to this.

happened again. is 6th August and data is only up to 3rd august.

you may need to have error check on dates for your cron Job, if not up to date due to pulling error from your system, you should be notified and remedy the situation. thanks

**Comment by amirmazmi** [comment]
@MoH-Malaysia , not sure how many of you are working on this but if you are struggling to manage this, I would suggest enlisting some help from community members (i am happy to help) to at least manage some of the more simpler aspects of this repo such as the issues and pull requests. Hopefully it will give you more time to deal with the cron and pipeline or any other issue in the backend. Thanks.

**Comment by NobodyButMe-Haiya** [comment]
> @MoH-Malaysia , not sure how many of you are working on this but if you are struggling to manage this, I would suggest enlisting some help from community members (i am happy to help) to at least manage some of the more simpler aspects of this repo such as the issues and pull requests. Hopefully it will give you more time to deal with the cron and pipeline or any other issue in the backend. Thanks.

we see it , but don't want to interfere .. i unsure why the reason 2 date late   or they don't want to be live before normal day  announcement.We not sure how they pump data manually or script  but we just make info using it and anybody want to implement it can copy and paste and modify themselve
