### ISSUE TITLE
Missing data in the pkrc.csv file

### ISSUE THREAD

**Issue by whykayfoo** [MoH-Malaysia/covid19-public#79]
Hi there,
Noticed in the pkrc.csv file - there are no data included at all for "states" WP KL and WP Putrajaya?
Why is this so?  I believe there are quarantine centres in both these territories.
Hope KKM is aware and will rectify this gap/ issue real soon.

Regards
Foo

**Comment by MoH-Malaysia** [comment]
Please check out the [documentation for PKRC data](https://github.com/MoH-Malaysia/covid19-public/tree/main/epidemic#pkrc-covid-19-quarantine-and-treatment-centre) - it explains this.
