### ISSUE TITLE
Request data of those positive but vaccinated

### ISSUE THREAD

**Issue by psyntium** [MoH-Malaysia/covid19-public#8]
This will help to see how effective the vaccination is. Can also breakdown by 1st dosage and fully vaccinated.

**Comment by MoH-Malaysia** [comment]
We have collated your request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md). Thank you for your input!

**Comment by dennislamcv1** [comment]
Thank you MoH for the population data as I need it for data analysis.
