### ISSUE TITLE
pkrc.csv - Column name typo

### ISSUE THREAD

**Issue by izzudinhafiz** [MoH-Malaysia/covid19-public#83]
File: pkrc.csv

Problem: Column names are mistyped
Affected: `discharge_pui`, `discharge_covid`, `discharge_total`

Comments:
Based on epidemic/README.md, the columns should be labeled `discharged_x`. This would also be more consistent with the hospital.csv data columns.

**Comment by MoH-Malaysia** [comment]
The column names are correct. Documentation is meant to describe it generally, rather than spell out the same thing 3 times.

**Comment by izzudinhafiz** [comment]
Understood.

However can the team reconsider renaming it for consistency? It'll be easier for downstream developer to make tooling such as API

**Comment by chonggs** [comment]
@MoH-Malaysia 
To clarify, I believe what @izzudinhafiz meant was: In file `pkrc.csv` the column names are missing 'D', whereas the README describes 'discharge**d**_' -- with 'D'. The issue does not happen in `hopsital.csv`.
