### ISSUE TITLE
tests_malaysia.csv - Column label has hidden TAB chars

### ISSUE THREAD

**Issue by izzudinhafiz** [MoH-Malaysia/covid19-public#85]
File: tests_malaysia.csv

Problem: Label `rtk-ag` and `pcr` has a hidden TAB character before it

Raw file snippet:
```
date, rtk-ag, pcr
2020-01-24,0,2
2020-01-25,0,5
```

ASCII Decode:

` rtk-ag` -> `009` `114` `116` `107` `045` `097` `103` (TAB R T K - A G)

**Comment by MoH-Malaysia** [comment]
Fixed - thank you!
