### ISSUE TITLE
Request for Additional Data Points - Daily Cases Breakdown by Category (1 to 5)

### ISSUE THREAD

**Issue by wayenyong** [MoH-Malaysia/covid19-public#86]
With the vaccination population going up and that we all know that vaccination will lessen the severity of the covid-19 patient... it will be very helpful to now
(1) have the breakdown by Cat 1 - asymptomatic  to Cat 5 - classifications provided. 
(2) within each Category, a further breakdown by Not Vaccinated, 1st Dose, and Fully Vaccinated

This will serve as another powerful communication message to general public who still NOT register for vaccination

**Comment by MoH-Malaysia** [comment]
Agreed - please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
