### ISSUE TITLE
Recovered Cases by State

### ISSUE THREAD

**Issue by marwan86** [MoH-Malaysia/covid19-public#90]
How to get the daily numbers of recovered cases for each state? The discharged numbers do not match the total recovered cases for all of Malaysia combined.

**Comment by mhlearn** [comment]
i thought it supposedly the sum of total discharged from hospital and pkrc, but seems not tally to what have announced as well.

**Comment by marwan86** [comment]
Yes, I tried different combinations, but nothing matched the total numbers of Malaysia. I think some recovered cases, such as those who are quarantined in their houses are not included.

**Comment by MoH-Malaysia** [comment]
@marwan86 is correct - the healthcare data only records those discharged from hospitals and PKRCs.

**Comment by marwan86** [comment]
I hope that you can add the recovered cases per state in the future so that the total numbers for all states match the ones published previously, such as the ones here, for example:
https://kpkesihatan.com/2021/05/22/kenyataan-akhbar-kpk-22-mei-2021-situasi-semasa-jangkitan-penyakit-coronavirus-2019-covid-19-di-malaysia/
