### ISSUE TITLE
Cluster End Date

### ISSUE THREAD

**Issue by NobodyButMe-Haiya** [MoH-Malaysia/covid19-public#92]
Can we get data cluster end date.Or if possible consider last updated timestamp  case total equal with recovered?

**Comment by MoH-Malaysia** [comment]
`date_last_onset` is what you're looking for.

**Comment by NobodyButMe-Haiya** [comment]
i ask it because the field information as symptom not cluster end date.
Some cluster still active and the onset date seem a bit weird to declare cluster is ended.

For me i want to put something like this week this cluster has ended , a positive vibe.
