### ISSUE TITLE
Total registered users for Mysejahtera per day

### ISSUE THREAD

**Issue by amirmazmi** [MoH-Malaysia/covid19-public#93]
Requesting a timeline of mysejahtera uptake in the form of total registered users per day. 
Please confirm if this data is available.

Will list this in CONTRIB.MD and submit pull request once confirmed that the data is available. 

Thanks.

**Comment by MoH-Malaysia** [comment]
We'll work on this - please make a data request [here](https://github.com/MoH-Malaysia/covid19-public/blob/main/CONTRIB.md#data-requests).
