### ISSUE TITLE
Clarification Needed, is there any adjustment will be made on RTK-Ag false positive cases data? 

### ISSUE THREAD

**Issue by ming86** [MoH-Malaysia/covid19-public#96]
From Issue #74 reply, the reported cases data are RT-PCR + RTK-Ag togather. 

RTK-Ag result could be false positive, after verified with RT-PCR.

The questing is, is there any adjustment will be made to the data for those RTK-Ag false positive cases data? 
How are the adjustment will be made?

**Comment by MoH-Malaysia** [comment]
There are no plans to release the data in this way thus far.
