### ISSUE TITLE
Seeking clarification for unique_ind on MySejahtera data

### ISSUE THREAD

**Issue by leelonghui3** [MoH-Malaysia/covid19-public#98]
Hi there, **unique_ind** is defined as the "number of unique accounts which checked in", may I know is it based on the number of check-in on location?

If one person check-in in three separate locations today (check-in twice in one of the locations), what is the unique individual count?

For example, if I check in once at supermarket A, it is counted as one. And I go to a bank later, I check in another time. But if I go back to supermarket A and checking in again, does it counted as another new check-in?

**Comment by MoH-Malaysia** [comment]
In your sample scenario, it would count as **1 unique individual**.

To hit home: If you divide total checkins by unique individuals, you get the average checkins per individual on that day.

**Comment by leelonghui3** [comment]
Thank you for the clarification
