### ISSUE TITLE
Age and gender data on death

### ISSUE THREAD

**Issue by TarmiziIzzuddin** [MoH-Malaysia/covid19-public#99]
Is it possible to get age and gender information for the number of death cases?

**Comment by softwareforenterprise** [comment]
To include age and gender information for the number of death cases would be useful.

If possible, would also like to see data if they are vaccinated (yes/no)

If yes, how many doses (1/2) and also the brand of vaccine. With this info, maybe can look into the efficacy of the vaccine by brand.

**Comment by chez1978** [comment]
We really need age and gender disaggregated data for both COVID-19 positive cases as well as death statistics. Is it possible to provide the microdata of COVID-19 death cases as shared before by sex, state, age and nationality? It would make it easier for us to splice the data. Without similar breakdowns by age and sex, it is impossible to calculate up-to-date death rates as well as infection rates. Thank you team!

![Death Statistics](https://user-images.githubusercontent.com/88547262/128523260-0aa656f6-d022-403d-b1a9-9be1c2daceda.png)

**Comment by MoH-Malaysia** [comment]
We're working on this!

**Comment by yosus** [comment]
dear moh, i think you can post all **raw-data** here (except sensitive info like IC) and the community can help you to organise  the data.

**Comment by sooxt98** [comment]
Any updates on this? It should include vaccination status and how many doses, and how many days after x doses of vaccine.
